### ISSUE TITLE
General - Set up proper back-end ENV imports instead of using the react app way

### ISSUE THREAD

**Issue by KincentLan** [Northeastern-Electric-Racing/FinishLine#1]
## Description

Configure back-end environment variable imports properly for local development. This will help ensure we are minimizing the chances of env variables being exposed publicly to users when they don't absolutely need to be. 

## Background

We used `create-react-app` to initialize our front-end React application, which includes `react-scripts` helper scripts to perform various helpful development things. One of these is support for environment variables, making it really easy to add usage of env variables by just creating a `.env` file and adding env variables that are prefixed with `REACT_APP_`. The way that React works means that these env variables will get bundled as hard-coded values in the files sent to the client browser. This exposes env variables to users when env variables are normally kept secret, introducing a necessary security vulnerability.

For the back-end, the only existing part is how Prisma automatically handles importing the `DATABASE_URL` specified in the `prisma.schema` file from the `.env` file. Because it does this out-of-the-box, it won't be useful in implementing this ticket, but is good for awareness.

## Proposed Solution

Examine Northeastern-Electric-Racing/FinishLine#9 and Northeastern-Electric-Racing/PM-Dashboard-v2#440 to understand how they are pulling env variables into the back-end. Potentially use the same implementation and confirm that it works properly.

Once you have a working solution, please report a list of all env variables used in the back-end so we can determine what changes to env variables might be needed. Changes to env variables currently always require involvement from @jamescd18 for administrator-level access.

**Comment by anthonybernardi** [comment]
the backend is no longer part of the create react app so this is obsolete
