### ISSUE TITLE
General - Dark Mode for Modals

### ISSUE THREAD

**Issue by jamescd18** [Northeastern-Electric-Racing/FinishLine#102]
### Browser(s)

Safari

### Platform(s)

Desktop

### Version(s)

production

### Observed Behavior

Dark mode doesn't work for modals
- activate cr
- stage gate cr
- review cr

### Expected Behavior

Dark mode works

### Steps to Reproduce

1. Go to unreviewed cr
2. Make sure you're in dark mode
3. Review cr

**Comment by anthonybernardi** [comment]
note: should maybe wait for switch to MUI to do this

**Comment by anthonybernardi** [comment]
MUI fixed this
