### ISSUE TITLE
General - Make `PageBlock` Collapsable

### ISSUE THREAD

**Issue by jamescd18** [Northeastern-Electric-Racing/FinishLine#103]
### Current Features

`PageBlock` components are static with required `headerRight`.

### Desired Additional Features

Make them collapsable with a little arrow in the top left corner, make them be able to be default closed. Then we'd need to go through and update all usages. This will help condense information on pages.

NOTE: This should be done on the MUI migration branch!

**Comment by oneal55** [comment]
I wasn't exactly sure how to test the state change for the component, but it works as far as I've tested.
