### ISSUE TITLE
Switch Project Lead to Lead on WP Details

### ISSUE THREAD

**Issue by RChandler234** [Northeastern-Electric-Racing/FinishLine#1037]
### Description

Right now, the work package details list lead and manager as Project Lead and Project Manager. These two are the lead and manager on the WP (not the project it is under), so this can be kinda confusing. The complete solution is to update these names everywhere else to just be lead and manager, but for now, we just wanna change the frontend portion to say just 'Lead' and 'Manager' respectively for Work Package Details.

### Acceptance Criteria

The labels under Work Package Details say 'Lead' and 'Manager' instead of 'Project Lead' and 'Project Manager'

### Proposed Solution

N/A

### Mocks

<img width="252" alt="image" src="https://user-images.githubusercontent.com/29521172/227095650-842dc993-ee4b-49a4-b68b-9a83baad2453.png">

**Comment by Boeufin** [comment]
bruh
