### ISSUE TITLE
Change Request Detail Cards

### ISSUE THREAD

**Issue by RChandler234** [Northeastern-Electric-Racing/FinishLine#1038]
![image](https://user-images.githubusercontent.com/29521172/227097726-c2e3df86-1981-436c-9cea-474634bc3fe9.png)
Change Request Cards will follow a standard format;
They will share the following details
In [NER RED], have the CRID
In [NER RED], [Heading size font], display | <WBS#> -
Below this, have the submissions section, which will have a label of "Submitted:", and display the submitter name and date to the right of this
Have a pill section to label the status, as one of ACTIVATION, DEFINITION_CHANGE, STAGE_GATE, ISSUE, or OTHER
Since change requests come in a variety of types, cards will reflect this

**Standard change request card**

Standard change requests will display a preview of their what, displaying up to 2 lines
They will also show a summary of their change requests, mainly in number and in status
Have a Header (header 3 size) to label the section as proposed solutions
Below this have a smart list, that will display how many proposed solutions have No Status. how many are Denied, and if it is approved, that there is 1 approved change request

**Stage Gate Change Request**

Stage gate change requests will display their leftover budget, and if the work package was completed, as a yes or no value
leftover budget and WP completion should be in one line, with the leftover budget on the left

**Activation Change Request**

In one line, the card will show the Project Lead and the start date
Below this, will be the Project Manager
For each of these, have a bolded identifier, with an adjacent text item displaying the relevant value

Implementation Details:
This card should be a new component in its own file in the ChangeRequestPage folder. It should only take a change request as a prop
<img width="134" alt="image" src="https://user-images.githubusercontent.com/29521172/227098154-2007245e-28e7-41e5-928a-b803e3835ccc.png">

**Comment by Ray-kong** [comment]
delete leftover budget - Reid

**Comment by jamescd18** [comment]
How I would redesign 
<img width="687" alt="image" src="https://user-images.githubusercontent.com/51571627/231910452-de88d0a0-e83c-4655-ac19-60a2ef9861b7.png">

**Comment by jamescd18** [comment]
<img width="637" alt="image" src="https://user-images.githubusercontent.com/51571627/231911365-1c1d18af-d7f8-4e41-995e-df6848b53671.png">

**Comment by jamescd18** [comment]
<img width="640" alt="image" src="https://user-images.githubusercontent.com/51571627/231912132-0a3ac466-622a-4ffa-a69c-0776d4d446b0.png">
