### ISSUE TITLE
Repository - Resolve Critical Package Vulnerabilities

### ISSUE THREAD

**Issue by jamescd18** [Northeastern-Electric-Racing/FinishLine#11]
### Background 
While development can continue to move forward package vulnerabilities present, these vulnerabilities should be addressed as they may pose security threats in the long run. Critical vulnerabilities pose the largest security threat and should be addressed first. We currently have two critical vulnerabilities that need to be resolved.

### Proposed Solution
- [ ] Run `npm audit` and view audit report
- [ ] Fix the two critical level vulnerabilities either automatically or manually according to suggestions from the adult report
- [ ] Ensure that fix does not break current build
- [ ] This site could be a helpful start: https://www.whitesourcesoftware.com/free-developer-tools/blog/npm-audit/

### Screenshots 

<img width="390" alt="Screen Shot 2021-12-27 at 7 58 27 PM" src="https://user-images.githubusercontent.com/51571627/147526455-a9bf4a5e-a1ad-470e-a2db-73c8cd63c6d9.png">

**Comment by Ari-S-123** [comment]
![image](https://user-images.githubusercontent.com/80832201/184198181-c04f09ea-dd7e-4a05-916c-35a48ff261ff.png)
