### ISSUE TITLE
Refactoring - Allow a project to be assigned to multiple teams

### ISSUE THREAD

**Issue by Peyton-McKee** [Northeastern-Electric-Racing/FinishLine#1162]
### Description

We want projects to be able to be assigned to multiple teams. 

### Acceptance Criteria

Schema Updated.
Change Backend to reflect this change. 
Change Frontend to reflect this change.

### Proposed Solution

Your gonna have to change the schema. probably the project edit backend, the assign to my team endpoint, and probably alot of other places. 

### Tickets
https://github.com/Northeastern-Electric-Racing/FinishLine/issues/1171
https://github.com/Northeastern-Electric-Racing/FinishLine/issues/1170

**Comment by RChandler234** [comment]
already done!
