### ISSUE TITLE
Heads should be able to edit tasks

### ISSUE THREAD

**Issue by RChandler234** [Northeastern-Electric-Racing/FinishLine#1187]
### Description

update the permissions in the frontend and backend so that heads can edit tasks

### Acceptance Criteria

heads can edit tasks

### Proposed Solution

N/A

**Comment by callmejim1226** [comment]
Hints to get this ticket started:

By tasks, we specifically mean a task in a certain project. For example, if we visit /projects/1.1.0/tasks page in our localhost:3000, we can see tasks listed for project 1.1.0, and on the right side, we see the `Actions `button which has an `Edit` button in it. 

For this ticket, we want the user who has the role of head to be able to click the edit button and edit the project. To do this, I recommend that we search the code for the `Actions` dropdown button and check the `Edit` button code. 

For the backend changes, check the function in the project's service folder which handles the project edit tasks.
