### ISSUE TITLE
General - Reexamine Pipes Design Pattern

### ISSUE THREAD

**Issue by jamescd18** [Northeastern-Electric-Racing/FinishLine#12]
## Description

Re-evaluate the current design of pipes in order to handle data that is not guaranteed to be present. Sometimes the values will be undefined, and none of the pipes currently are set up to handle possibly undefined values given that our type system typically eliminates the possibility of undefined values (by way of defining undefined as a separate type).

## Background

There is an em-dash pipe that solves the issue for when there is an empty string, however, this does not quite solve the problem.

## Desired Changes

What we want is a construct sufficiently flexible so that we can have reusable functions to control the display of individual values. The pipes functions currently serve this purpose by centrally defining how dates, dollars, or names should be displayed. We also need a sufficiently flexible way to handle values that may or may not be present.

What we want is to check values and immediately short circuit to displaying an em-dash (or potentially in the future we may want alternatives to an em-dash) if the value is undefined. Otherwise, we want to continue and process the value to display according to the pipe.

## Proposed Solution

- [ ] Re-evaluate design pattern of pipes
- [ ] Write a brief description of your proposed modifications to this design pattern as a comment on this ticket
- [ ] Review proposal with your squad's lead & make improvements to the proposal
- [ ] Review proposal with James Chang-Davidson & make improvements to the proposal
- [ ] Implement changes to the design pattern according to your proposal

**Comment by anthonybernardi** [comment]
this issue is way too vague
