### ISSUE TITLE
Request a CR Reviewer - Backend Slack Integration

### ISSUE THREAD

**Issue by RChandler234** [Northeastern-Electric-Racing/FinishLine#1202]
### Description

Blocked by #1200, #1201

Update the request CR reviewer endpoint so that it also sends a slack notification to the user saying that they have been requested as the reviewer on a CR.

### Acceptance Criteria

The request a CR reviewer endpoint now also sends a slack notification to the user sent in its payload as well.

### Proposed Solution

This new functionality should go in a service or util function that is called in the service method for the request CR reviewer endpoint. You'll need the slack bot credentials to test this so @RChandler234 in #software to get those. See sendSlackUpcomingDeadlineNotification in slack.utils/ where it is called for an example of how to send slack messages with the bot.

**Comment by Peyton-McKee** [comment]
Completed in #1201
