### ISSUE TITLE
Work Package Templates - Investigate different kinds of Work Package templates

### ISSUE THREAD

**Issue by Peyton-McKee** [Northeastern-Electric-Racing/FinishLine#1205]
### Description

A cool idea that Nick De Patie suggested was project templates as alot of work packages have the same expected activities and deliverables and every work package is blocked by the one before it. 

### Acceptance Criteria

Discuss with different engineering heads possibilities for work package templates. Find out if there are any other ones like PCBs that we could make a template for. 

### Proposed Solution

Slack message

## Tickets

 - [ ] Make front-end
 - [ ] Make back-end
 - [ ] Wire

**Comment by RChandler234** [comment]
we been done
