### ISSUE TITLE
Projects - Remove Stored Project Status

### ISSUE THREAD

**Issue by jamescd18** [Northeastern-Electric-Racing/FinishLine#122]
## Overview

Instead of storing project status as a variable, make it calculated based on work package statuses.

## User Story

As a project manager, I want to quickly update a project so everyone knows that it is now active, with as few steps as possible.

## Current Features

Currently, a project's status is based on a enum variable stored in the database. This means it must be manually updated by users whenever the project's status changes. 

## Reasoning

Separately updating the project status is unnecessarily cumbersome and annoying for users because it is additional step on top of having to update work packages to be marked as active. This leads to projects being not properly marked with their correct status, and subsequently results in unneeded confusion about which projects are active.

## Desired Changes

Entirely remove the project status variable from the database model. Instead, make the back-end calculate the project status based on the project's work pacakges' statuses as follows:

- if any work package is `ACTIVE`, then the project is `ACTIVE`
- if all work packages are `COMPLETE`, then the project is `COMPLETE`
- otherwise, the project is `INACTIVE`

**Comment by anthonybernardi** [comment]
Note: there is also the easier solution of just ignoring the acutal status of the project on the frontend and calculating and displaying it based off of the given criteria. If you pick this ticket up, make sure to check in with me and james about it
