### ISSUE TITLE
Look into replacing axios with fetch

### ISSUE THREAD

**Issue by RChandler234** [Northeastern-Electric-Racing/FinishLine#1234]
### Goal

Get rid of a package!

### Reason for Spike

cause it'd be cool to get rid of package

**Comment by ninest** [comment]
https://caniuse.com/fetch

https://blog.logrocket.com/axios-vs-fetch-best-http-requests/

> Axios provides an easy-to-use API in a compact package for most of your HTTP communication needs. However, if you prefer to stick with native APIs, nothing stops you from implementing Axios features.
>
> As discussed in this article, it’s perfectly possible to reproduce the key features of the Axios library using the fetch() method provided by web browsers. Ultimately, whether it’s worth loading a client HTTP API depends on whether you’re comfortable working with built-in APIs.

**Comment by Peyton-McKee** [comment]
i used fetch for getting downloading the images to files, but isnt axios good because it abstracts fetch to make it easier to work with
