### ISSUE TITLE
Finance Fixes - Default Account to Budget

### ISSUE THREAD

**Issue by Peyton-McKee** [Northeastern-Electric-Racing/FinishLine#1276]
### Description

Users should be using the budget account for pretty much all purchases, so the default should be budget not cash

### Acceptance Criteria

default is budget

### Proposed Solution

edit the default value in the create RR form
epic #1274

**Comment by abhinaisai2002** [comment]
I would like to work on this

**Comment by Peyton-McKee** [comment]
@abhinaisai2002 Are you in the slack?

**Comment by abhinaisai2002** [comment]
No

**Comment by Peyton-McKee** [comment]
Are you a northeastern student?

**Comment by abhinaisai2002** [comment]
No, I am not a student. I am from India

**Comment by Peyton-McKee** [comment]
Unfortunately you have to be a Northeastern Student to contribute as of now, I appreciate you reaching out.
