### ISSUE TITLE
Finance Fixes - details display overflow

### ISSUE THREAD

**Issue by RChandler234** [Northeastern-Electric-Racing/FinishLine#1297]
fix this:
<img width="544" alt="image" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/29521172/fcc7acd5-c8f7-47aa-a432-d8b178711bff">

**Comment by martin0he** [comment]
I have 2 ideas to do text overflow:
1. Horizontal scrollbar
2. regular overflow

Let me know which is preferred so I can implement it.
my examples: 
Scrollbar:
https://github.com/Northeastern-Electric-Racing/FinishLine/assets/90310958/bad52aa2-ca0d-4318-9103-340eb44a21d8

Resize:
https://github.com/Northeastern-Electric-Racing/FinishLine/assets/90310958/4948e6ff-a7f4-4dae-9400-e7aac3a54869
