### ISSUE TITLE
Page Block Redesign

### ISSUE THREAD

**Issue by Peyton-McKee** [Northeastern-Electric-Racing/FinishLine#1316]
### Overview

We are redesigning our frontend to no longer use pageblocks due to their ugly appearance and limited creative flexibility. 

### Stakeholders

Product Stakeholder: Peyton McKee, Zach Marino
Software Stakeholder: Reid Chandler, Peyton McKee
Reference Users: N/A

### User Story

As a finishline lover, I want a good looking application, so that I actually enjoy doing project management.

### Success Metrics

People compliment us on our new amazing views

### Rollout Plan

1. New Project / Work Package Form
2. Change Request Redesign
3. Gantt Chart Redesign
4. Home Page Redesign
5. Teams Page Redesign
6. Settings / Admin Tools Redesign

### Out of Scope

editing any pages that have been changed to no longer use page blocks

### Background / Context

We’ve migrated the project and work package views to no longer use page blocks and we want to continue redesigning pages to no longer use them so that our app doesn’t look as rigid and blocked off. 

### Acceptance Criteria & Mock-ups

No more page blocks anywhere in the app
Specific Mockups will be used in each individual epic

### Tickets

 - [x] #1317 
 - [x] #1318

**Comment by RChandler234** [comment]
initial scope of this epic is done
