### ISSUE TITLE
Project Form Redesign - Alter Create Project Endpoint to include updated fields

### ISSUE THREAD

**Issue by Peyton-McKee** [Northeastern-Electric-Racing/FinishLine#1320]
### Description

Since we are now using one form, the create project endpoint needs to be updated to take in all the information on this form. 

### Acceptance Criteria

Accepts the following fields
- [x] Project Name - Non empty String
- [x] Change Request Id - Int min Zero
- [x] Car Number - Int min Zero
- [x] Team Ids - [Int min Zero]
- [x] Budget - Int min Zero
- [x] Project Summary - Non empty String
- [x] Project Lead Id - Int Min Zero
- [x] Project Manager Id - Int Min Zero
- [x] Links - [{url: Non Empty String; linkTypeName: Non empty String }]
- [x] Goals - [{id: Int min -1; detail: non empty string}\
- [x] Features - same as goals
- [x] Other Constraints - same as goals
- [x] Rules - same as goals

### Proposed Solution

Alter the route to correctly accept these fields (can probably copy and paste the edit route). Alter the controller to parse them out of the route and send them to the service function. Update the service function so that it creates the project with these fields in the database

Branch off of the feature/Project-Form-Redesign branch

epic #1317

**Comment by RChandler234** [comment]
merged
