### ISSUE TITLE
Project Form Redesign - Goals, Features, Other Constraints, Rules

### ISSUE THREAD

**Issue by Peyton-McKee** [Northeastern-Electric-Racing/FinishLine#1324]
### Description

Since these all use ReactEditableList you will only have to edit that component in order to achieve the desired affect since they all look the same

### Acceptance Criteria

Looks like the mock

### Proposed Solution

Edit the React Editable List component to look like the mockup, Do not edit any of the useFieldArray Stuff other than moving the containers around

Work off of the feature/Project-Form-Redesign Feature Branch

### Mocks

Old Version
<img width="740" alt="Screen Shot 2023-09-05 at 6 27 32 PM" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/113635669/cb86055a-3cbf-4b68-b9f0-4d357bce98fb">

New Version
<img width="692" alt="Screen Shot 2023-09-05 at 6 27 46 PM" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/113635669/2e2b6eea-4562-4183-8e07-9bf2728024ff">

epic #1317

**Comment by RChandler234** [comment]
done
