### ISSUE TITLE
Work Package Redesign - Delete Create Work Package Page Folder

### ISSUE THREAD

**Issue by Peyton-McKee** [Northeastern-Electric-Racing/FinishLine#1326]
### Description

Were gonna be working off of the create work package page so we dont need to worry about these files anymore 

### Acceptance Criteria

folder is deleted

### Proposed Solution

right click; delete folder

src/frontend/src/pages/createworkpackagepage

work off the feature/Workpackage-Form-Redesign Branch

### Mocks

epic #1318

**Comment by RChandler234** [comment]
done
