### ISSUE TITLE
Work Packages - Investigate Alternate Gantt Chart Packages

### ISSUE THREAD

**Issue by leoRysing** [Northeastern-Electric-Racing/FinishLine#135]
## Spike Type

Technical

## Goal

Our goal is to switch over our existing Gantt chart package. At the successful conclusion of this epic, our work package Gantt charts will be swapped over to a selected new react package. No functionality will be lost, and Display dates will be changed from Sundays to Mondays. This package will be recorded as the new standard for our Gantt charts moving forwards

## Reason for Spike

As brought up by James and Anthony, we aren't too satisfied with the defacto bootstrap Gantt chart package we have been using. It isn't very intuitive and hard to customize for our needs. As such, we need to swap from it.

## Additional notes

We have some packages that Anthony has initially identified in React;
- [Frappe](https://github.com/frappe/gantt)
- [MaTeMaTuK](https://github.com/MaTeMaTuK/gantt-task-react)
- [ANovokmet](https://github.com/ANovokmet/svelte-gantt)
- [Bignumlock](https://github.com/bignumlock/react-gantt-elastic)

**Comment by anthonybernardi** [comment]
Tested out Frappe, does not have good Typescript/React support

**Comment by anthonybernardi** [comment]
![image](https://user-images.githubusercontent.com/63663597/187471083-ce733ab0-2d87-4c5f-b5d2-d3b12c1ac89e.png)

**Comment by anthonybernardi** [comment]
this package is good enough, future tickets should use my pr as a starting point https://github.com/Northeastern-Electric-Racing/FinishLine/pull/160
