### ISSUE TITLE
Gantt - Investigate Critical Path

### ISSUE THREAD

**Issue by leoRysing** [Northeastern-Electric-Racing/FinishLine#136]
### Spike Type

Functional, Technical

### Goal

Figure out how, with the new Gantt chart implementation, we can show a critical path. Add this to our work package gantt visuals and ensure that the necessary backend changes are made to support this.

Make sure to note how to extend this to projects, and add backend support for this.

### Reason for Spike

Critical Path is a very important visual for our Gantt chart. In the existing Spreadsheet tool, this provides necessary context about how projects and work packages fit together, beyond just how they fit in on a timeline. As such, we must be able to translate this, if we hope to swap completely over to the dashboard. 

### Additional notes

This ticket has a prerequisite, which is the previous ticket;
- [ ] #135 

A helpful reading about critical path can be found [here](https://blog.ganttpro.com/en/critical-path-gantt-chart/), and an example of critical path in a Gantt chart is below.
<img width="832" alt="Screen Shot 2022-08-17 at 6 13 20 PM" src="https://user-images.githubusercontent.com/9142777/185253046-9f4c4bbf-ec78-4b75-bf53-2107a9732b12.png">

**Comment by anthonybernardi** [comment]
it's in this pr https://github.com/Northeastern-Electric-Racing/FinishLine/pull/160
