### ISSUE TITLE
Project Details - Display Associated Teams

### ISSUE THREAD

**Issue by walker-sean** [Northeastern-Electric-Racing/FinishLine#1514]
### Description

Currently, our teams' detail pages display the projects associated with them, but the reverse is not true. Add a list of the teams associated with a project on the Projects Detail Page

### Acceptance Criteria

Projects detail pages display a list of the teams associated with them (as links to each team's detail page)

### Proposed Solution

This could be added to the Details section of the page

**Comment by RChandler234** [comment]
looks like this ticket exists already, and has been kicking around for a fat ass minute, looks like someone is assigned to it now tho; Thank u for making this tho Sean, I fw the energy
