### ISSUE TITLE
Reimbursement Request Form - Make File Dialog Multi-File

### ISSUE THREAD

**Issue by walker-sean** [Northeastern-Electric-Racing/FinishLine#1555]
### Description

Currently, when a user is making a reimbursement request, they must select a single file at a time when uploading their receipts. We want the user to be able to select multiple files to upload at once

### Acceptance Criteria

- The file dialog in the reimbursement request form allows the user to choose multiple files at once
- Each selected file is uploaded and displayed as uploaded in the 'Receipts' list

### Proposed Solution

- Add the `multiple` prop to the file `input`
- Make the `onChange` function append each file to the list of receipts

**Comment by martin0he** [comment]
this already works
