### ISSUE TITLE
[Frontend] - Right Align Pencil Icons

### ISSUE THREAD

**Issue by tigerhippo** [Northeastern-Electric-Racing/FinishLine#1596]
### Description

Right now, on an individual Team's page (to get there, you click on Teams and then 'See More' under any team), in the People section, the pencil icons are all located right next to the people's names. This doesn't look the most visually appealing for the user and seems a little disorganized.

### Acceptance Criteria

The pencil icons should all be vertically aligned on the right side of the People section (for all the teams). 

### Proposed Solution

N/A

### Mocks

All three of these pencil icons should be vertically aligned on the right side of the People section, right now only the last two are.

![Image](https://github.com/Northeastern-Electric-Racing/FinishLine/assets/60333735/af23f94f-c587-4f61-a7e7-07de09ccbaea)

**Comment by RChandler234** [comment]
done in another ticket
