### ISSUE TITLE
General - Improve Message Body Responses

### ISSUE THREAD

**Issue by jamescd18** [Northeastern-Electric-Racing/FinishLine#16]
### Description

Improve how message body responses are created and utilized by abstracting the current implementation one level higher.

### Proposed Solution

- [x] Create an interface for message responses `{ message: string }`
- [x] Create another response builder function for creating message responses that takes in two parameters (response code and string message)
- [x] Refactor existing back-end responses and response builder functions to better utilize this new message pattern
- [ ] Refactor some front-end items to actually use the newly created message response interface instead of just the inline definition

_Originally posted by @KincentLan in https://github.com/Northeastern-Electric-Racing/PM-Dashboard-v2/pull/448#discussion_r785379165_

**Comment by anthonybernardi** [comment]
imo not needed now with express, just have to ensure all res.json have a {message: } field
