### ISSUE TITLE
Change Request activation details page redesign

### ISSUE THREAD

**Issue by ryanhowe28** [Northeastern-Electric-Racing/FinishLine#1639]
### Current Features
branch off feature/Change-Request-Redesign for feature branch

![image](https://github.com/Northeastern-Electric-Racing/FinishLine/assets/102765855/d0384f17-5964-4c90-a690-33340398fff5)

### Desired Additional Features

We want to remove the page blocks for the Change Request details and the Activation Details and make the information look nicer. This is for the Activation type of Change Requests (separate page than others)

### Screenshots (as needed)

![image](https://github.com/Northeastern-Electric-Racing/FinishLine/assets/102765855/5b8a3f32-d1bc-4ec5-9d2b-fdaad63002b8)

Epic https://github.com/Northeastern-Electric-Racing/FinishLine/issues/1645
branch off Change-Request-Redesign for feature branch
Message Zach Marino in slack for any design questions!

**Comment by RChandler234** [comment]
I don't think we actually care about displaying the yes or no for confirm WP details after talking to engineers @martin0he
