### ISSUE TITLE
General - Improve Error Handling in Back-End

### ISSUE THREAD

**Issue by jamescd18** [Northeastern-Electric-Racing/FinishLine#17]
## Description

Currently there are some places where there are either explicit or implicit errors thrown on certain conditions where the input is invalid or bad in some way, we would like either catch or prevent these errors so we can return a 4xx (IE error 404) response rather than the 5xx response currently given from the http error handling middleware. 

## User Story

As a project manager, I want to see more helpful error messages that can be useful for me. If an action I take causes an error, I want to be able to understand what happened and potentially be able to fix it on my own, and only need to include the software team in an investigation if the problem is outside my power.

## Proposed Solution

Maybe a try catch would be good here to ensure proper error handling. We do not want to send message success on error.
There is also a need to come up with better error messages in general so we don't have to guess at what broke.

## Tickets

These errors need better error messaging. Each error corresponds to one ticket:
- [x] Northeastern-Electric-Racing/FinishLine#47
- [x] Northeastern-Electric-Racing/PM-Dashboard-v2#547 

_Originally posted by @KincentLan in https://github.com/Northeastern-Electric-Racing/PM-Dashboard-v2/pull/448#discussion_r785379190_

**Comment by anthonybernardi** [comment]
both tickets are done
