### ISSUE TITLE
[Frontend] - Members list should be limited to users of role member

### ISSUE THREAD

**Issue by ninest** [Northeastern-Electric-Racing/FinishLine#1705]
### Description

Currently, the members and leads autocomplete list shows users of all roles

<img width="1016" alt="image" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/34677361/1c4d946d-e609-4723-a251-bc4786199d3b">

### Acceptance Criteria

- the members autocomplete list should only show users with the role "member"
- the leads autocomplete list should only show users with the role "lead"

### Proposed Solution

Edit the `TeamMembersPageBlock` component, specifically, the `EditingMembersView`'s member options.

### Mocks

None

**Comment by RChandler234** [comment]
don't actually wanna do this
