### ISSUE TITLE
[Frontend] - Add 'Create New Workpackage' Button to Action Dropdown on a Project

### ISSUE THREAD

**Issue by RChandler234** [Northeastern-Electric-Racing/FinishLine#1762]
### Description

Right now the only way to create a work package is to know that you need to create a change request for it, create that change request, then make that work package off that change request. Instead, we want to add an option to the actions dropdown on an individual project page that takes you to a change request that has been filled out with all the necessary details. The CR should be an ISSUE CR, with a why reason - initialization: Creating a Work Package on this Project. 

### Acceptance Criteria

- [x] There's a button added to the action dropdown on a projects page labelled 'Create Work Package' with a ContentPasteIcon
- [x] It should lead to the change request page with the values specified above already filled in

### Proposed Solution

See how we do 'suggest budget increase' to see how you can prefill a change request with values.

### Mocks

N/A

**Comment by yulanwang** [comment]
Added a button to the action dropdown called 'Create Work Package' with a ContentPastelIcon, but having trouble with it leading to a change request page with the specified values filled in. Currently, it only leads to a standard new change request page with the why reason set to Other.
