### ISSUE TITLE
Quantity Should be a Decimal - Backend

### ISSUE THREAD

**Issue by RChandler234** [Northeastern-Electric-Racing/FinishLine#1782]
### Description

Blocked by #1780 

We want quantity on a material (bill of materials) to be a decimal instead of an int. This ticket is to update all the backend types to expect a decimal value for quantity rather than an int.

### Acceptance Criteria

- [ ] All the backend endpoints for creating or fetching a material expect a decimal value rather than an int

### Proposed Solution

This is a good ticket to familiarize yourself with the backend. The changes themselves will be pretty small, but it'll allow you to see the whole flow of data in the backend

### Mocks

N/A

**Comment by Aaryan1203** [comment]
Already completed when doing the schema change
