### ISSUE TITLE
Quantity Should be a Decimal - Frontend

### ISSUE THREAD

**Issue by RChandler234** [Northeastern-Electric-Racing/FinishLine#1783]
### Description

Blocked by #1781 

We want quantity on a material (bill of materials) to be a decimal instead of an int. This ticket is to update all the frontend types to expect a decimal value for quantity rather than an int.

### Acceptance Criteria

- [ ] All the stuff in the frontend expects a decimal value for quantity rather than an int

### Proposed Solution

This is a good ticket to familiarize yourself with the frontend. The changes themselves will be pretty small, but it'll allow you to see the whole flow of data in the frontend

### Mocks

See where quantity is used on this page (for when u manually test this)
<img width="960" alt="image" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/29521172/59414444-33c1-4da4-8f2b-124786d672c1">

**Comment by Aaryan1203** [comment]
Already completed when doing the schema change
