### ISSUE TITLE
Auto Implementing CRs - Create New Work Package Button

### ISSUE THREAD

**Issue by Peyton-McKee** [Northeastern-Electric-Racing/FinishLine#1896]
### Description

Blocked By #1894, but you can start on the frontend form before it's done if you want

We want to make a streamlined way for users to make a new work package. On a project detail page there should be a 'Create New Work Package' button. When clicked the button should take you to a version of the work package form that when submitted creates an initialization change request with the correct associated wbs proposed changes and work package proposed changes. 

### Acceptance Criteria

- [ ] Create New Work Package button links to a new form
- [ ] New form sends the inputs from the form to the create scope cr endpoint
- [ ] The form should spit the user out on the my cr overview page once submitted

### Proposed Solution

Implementation note: we'll be able to tell it's a work package create in the review because it'll have work package proposed solutions on a crID associated with a project

**Comment by RChandler234** [comment]
done
