### ISSUE TITLE
CR Feature - Edit Create work package Endpoint

### ISSUE THREAD

**Issue by Peyton-McKee** [Northeastern-Electric-Racing/FinishLine#1897]
### Description

We need to accept the newly added CR_Status to wbs elements so we need to adjust the endpoints to include the cr_status

### Acceptance Criteria

- [ ] Adjust routes to take in the crStatus field 
- [ ] Create validation function to validate that the status is a valid cr status
- [ ] adjust controllers to parse the status and insert them into the service functions
- [ ] Adjust service functions to add the crStatus to the newly created wbselement

### Proposed Solution

llook at how we validate roles in validation.utils

**Comment by RChandler234** [comment]
changed implementation
