### ISSUE TITLE
New CR Feature - Edit Create Project Endpoint

### ISSUE THREAD

**Issue by Peyton-McKee** [Northeastern-Electric-Racing/FinishLine#1900]
### Description

We need to edit the create project endpoint to take in a crStatus 

### Acceptance Criteria

- [ ] route takes in cr status and validates it with custom enum validation function
- [ ] controller parses and forwards cr status to service function
- [ ] service function adds the cr status to the prisma call to create the project

### Proposed Solution

^

### Mocks

epic #1892

**Comment by RChandler234** [comment]
changed implementation
