### ISSUE TITLE
Auto Implementing CRs - Validate All New Functionality

### ISSUE THREAD

**Issue by Peyton-McKee** [Northeastern-Electric-Racing/FinishLine#1906]
### Description

Reid Sean or Myself Should go through the feature branch and cleanup all the code and settle any merge conflicts / validate all test cases

### Acceptance Criteria

validate the following 
- [ ] Create a Project with an already approved Cr
- [ ] Create a project through new feature
- [ ] Create a work package with an already approved cr 
- [ ] Create a work package with new feature
- [ ] Create change request on a wbs element that already has a change request
- [ ] probably more shit 

### Proposed Solution

^

### Mocks

epic #1892

**Comment by RChandler234** [comment]
already done
