### ISSUE TITLE
Risk Log - Rename and Move Risk-Log Checklist

### ISSUE THREAD

**Issue by RChandler234** [Northeastern-Electric-Racing/FinishLine#199]
## Description

The current checklist component is very specific to the risk log feature; thus, it make sense to rename it to RiskLogCheckList to reflect that and move it to the projectviewcontainer with the risklog.tsx file since it likely won't be used anywhere else.

## Background

The initial design of the risk log created the checklist with hope to generalize, but with the current status we want to reorganize the location of this component and improve the package structure

## Proposed Solution

TODO

**Comment by Ari-S-123** [comment]
Implemented by https://github.com/Northeastern-Electric-Racing/FinishLine/pull/151
