### ISSUE TITLE
Change Requests - Add Project Name as Table Column

### ISSUE THREAD

**Issue by kevinyu328** [Northeastern-Electric-Racing/FinishLine#20]
### Description

Add a new column to the change request table that displays the name of the project the change request is associated with.

## User Story

As a project manager, I want to quickly understand what project a change request is associated with, without having to look up the project by its WBS #.

## Business Logic

Add a column to the change request table that displays the project name. 
- The column should be in-between the WBS# and Date submitted column that currently exists. 
- The column header should be "Project". 
-  If a CR is registered on a project, it displays the project’s name. If the CR is registered on a work package, it still displays the project's name

## Proposed solution

- update the `shared` change request type to include the `projectName` field
- modify the change request transformer to include this data
- add the column on teh change requests table page

**Comment by Peyton-McKee** [comment]
duplicate
