### ISSUE TITLE
Change Requests - Add Option to Edit Work Package / Project from Implement Change Requests Dropdown

### ISSUE THREAD

**Issue by leoRysing** [Northeastern-Electric-Racing/FinishLine#200]
## Current Features

There is no option to do this as of now. A user has to copy the CRID, go to the work package or project, go into the edit mode, then copy in the change request.

## Desired Additional Features

Add an option in the implement change request dropdown to edit WP / project. this should be flexible, and will display the correct option depending on the change request. When this button is clicked, it should take you straight into the edit mode of the WP / Project, with the CRID autofilled:)

## Mocks

<img width="675" alt="Screen Shot 2022-09-13 at 1 07 33 AM" src="https://user-images.githubusercontent.com/9142777/189813918-878f9d45-4c7c-472e-9e54-8dbe63c45d83.png">

**Comment by anthonybernardi** [comment]
i did this separately, didn't realize it was a ticket already
