### ISSUE TITLE
Change Request - Create Modal for Proposed Solution Creation

### ISSUE THREAD

**Issue by leoRysing** [Northeastern-Electric-Racing/FinishLine#203]
## Description 

Create the modal needed to submit a new proposed solution to a change request.

## Business Logic

When you click add a proposed solution, open up a new modal. In this model, there should be four input boxes. The first (on the left) should ask for the description, which should be some string input. Bellow this, there should be an input box for the scope. This should also be a text input box. To the right of these two, there should be input boxes for the budget (integer) and timeline (integer) impact for this proposed solution. To close this modal, you should click submit / add, which will be a button on the bottom right of the modal.

## Mocks

*To be done:)*

**Comment by anthonybernardi** [comment]
Ari already did this here actually https://github.com/Northeastern-Electric-Racing/FinishLine/pull/191
