### ISSUE TITLE
General - Find out why dates are inconsistent

### ISSUE THREAD

**Issue by anthonybernardi** [Northeastern-Electric-Racing/FinishLine#204]
### Problem

Dates are very inconsistent because we don't have a standardized day of dealing with them. For example, you might submit a change request on 9/15 and then it will get displayed as being created on 9/16 or something. Th exact cause of this is not known but I think it has to do with like say you submit a time on Eastern time zone, the backend when we give it a date assumes it is UTC, then when it sends it back it sends it as UTC and your browser converts it from UTC to Eastern. I'm not sure if this is exactly what's happening, but it's my best guess.

https://github.com/prisma/prisma/discussions/4153 this link shows that prisma's default time it creates is UTC, so this kinda backs up what I'm thinking where it seems to assume any time is in UTC even though we're passing it an EDT time.

### Steps to Reproduce

1. edit a work package start date or something to be a different day
2. see that it might show up wrong
3. this may or may not work depending on your time zone and your time of day

it happened to me in this pr here: https://github.com/Northeastern-Electric-Racing/FinishLine/pull/198

### Acceptance Criteria

What you should be doing in this ticket is seeing how to keep the exact time when you go from frontend input to backend output and back to frontend again. This will probably take a lot of console.logs or something and learning how javascript treats dates and timezones. If we can figure out the best process for keeping the same exact time throughout and exactly what is happening, we can fix it everywhere in another ticket. This ticket is just aiming to find out the WHY

**Comment by z-roth** [comment]
anthony pls fix
