### ISSUE TITLE
Admin Tools and Settings Redesign

### ISSUE THREAD

**Issue by AdityaBoddepalli** [Northeastern-Electric-Racing/FinishLine#2127]
### Overview

Epic for transforming the current Admin tools and setting page into a tab view

### Success Metrics

N/A

### Rollout Plan

Merge changes into a feature branch, and then release it.

### Background / Context

N/A

### Acceptance Criteria & Mock-ups

N/A

### Tickets

 - [x] #2128 
 - [x] #2140
 - [x] #2141  
 - [x] #2142 
 - [x] #2152 
 - [x] #2145 
 - [x] #2146 
 - [x] #2147

**Comment by RChandler234** [comment]
done!
