### ISSUE TITLE
Change Requests - Automate Proposed Solutions

### ISSUE THREAD

**Issue by leoRysing** [Northeastern-Electric-Racing/FinishLine#230]
### Overview

Automate relevant features for the Change Request automation implementation with the new proposed solution feature in mind.

### Stakeholders

Product Stakeholder:
Software Stakeholder:
Reference Users:

### User Story

As a _____, I want _____, so that _____.

### Success Metrics

Measuring correct usr of the feature

### Rollout Plan

Integrate, collect, analyze

### Out of Scope

-

### Background / Context

Currently, we are working on adding in a new model to support proposed solutions for change requests that use this model. This enables a more specific approval process for changes, where you can really approve and review multiple solutions of one change. As of now, this feature has been very barebones in terms of flow and ease, so we want to include automation to facilitate the process.

### Acceptance Criteria & Mock-ups

List of everything to be tracked:
- 

### Tickets

 - [ ] #
 - [ ] #

**Comment by anthonybernardi** [comment]
this never got filled out and james made a separate ticket for it and peyton completed it
