### ISSUE TITLE
DRC Debugs - Should send ping in relevant team channel when DR created

### ISSUE THREAD

**Issue by RChandler234** [Northeastern-Electric-Racing/FinishLine#2348]
Add functionality to the create design review endpoint, so that a ping is sent to the slack channel(s), associated with the submitted work package (see how we do it for pinging when a CR is created, should be the same sort of logic)

**Comment by RChandler234** [comment]
You should also send a message in #leads, #mechanical, and #electrical, we're probably going to have to add environment variables or a database model/ a new feature to allow chiefs to configure this

**Comment by RChandler234** [comment]
```
enum Slack_Config_Type {
  DESIGN_REVIEW
  CHANGE_REQUEST
}

model Slack_Config {
  slackConfigId   String            @id @default(uuid())
  type            Slack_Config_Type 
  slackChannelIds String[]
  team             Team
  teamId      
}
```

**Comment by Peyton-McKee** [comment]
completed via #2373
