### ISSUE TITLE
[Bug] - Unecessary Duplicate Tab for All Club Refunds

### ISSUE THREAD

**Issue by superhvarn** [Northeastern-Electric-Racing/FinishLine#2432]
### Description
There are 2 "all club refunds" tabs and we only need one.
<img width="1116" alt="Screenshot 2024-05-19 at 8 40 16 PM" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/56454934/85dc55d8-d423-4910-aeed-5b7fa2be2ee8">

### Acceptance Criteria

1. Remove the duplicate tab
2. Fix any frontend references to the duplicate tab

### Proposed Solution
Delete the extra tab in the react component that displays info for refunds and fix everything that refers to it

**Comment by Peyton-McKee** [comment]
completed via #2497
