### ISSUE TITLE
[Gantt Chart] Add New Project Button

### ISSUE THREAD

**Issue by Aaryan1203** [Northeastern-Electric-Racing/FinishLine#2500]
### Desired Changes

We want the ability to create a new project from the gantt chart with a new project button at the team level. 

### Acceptance Criteria
-  Button next to save that is add new project that creates a modal to allow a user to fill in the bare minimum amount of information to create a project which i believe is just a name and a summary. then default everything else to be either zero, an empty list and then the team that is currently being edited that you pressed the new project button from

**Comment by Peyton-McKee** [comment]
encompassedin #2422
