### ISSUE TITLE
DRC Debugs - Should be able to set the date/time by clicking a square on the availability heatmap

### ISSUE THREAD

**Issue by RChandler234** [Northeastern-Electric-Racing/FinishLine#2505]
### Description

In the design review detail page, clicking on a square on the heatmap should set the scheduled date and time of the design review to that time

### Acceptance Criteria

- [ ] You can select a date and time by clicking a square on the heatmap on the design review edit page

### Proposed Solution

You got this!

**Comment by Peyton-McKee** [comment]
completed via #2659
