### ISSUE TITLE
General - Upgrade dependencies

### ISSUE THREAD

**Issue by acd124** [Northeastern-Electric-Racing/FinishLine#26]
## Description

Currently we have a lot of dependencies that are not very organized, and include many deprecated packages and older versions of packages with potential or known vulnerabilities. Additionally some of these outdated dependencies don't work well with newer versions of node. We also have not particularly spelled out anywhere what version of node we are using for things like GitHub workflows, developer environments, and deployment.

## Background

Things to research before tackling this issue may include: 
- [ ] npm dependency trees
- [ ] the difference between dev dependencies and regular dependencies
- [ ] netlify/aws deployment environments
- [ ] node version managers
- [ ] our scripts in the package.json 
  - [ ] how they are used in development and deployment.

## Proposed Solution

At a high level the solutions would involve 3 main steps:
- Research and remove/replace deprecated dependencies
- Upgrade and refactor for outdated dependencies
- Document the node version and how to install it or change it

Each step can be broken into many steps of research into each dependency, consideration of whether or not it should be removed and why, what other things it affects and what needs to change because of it, and the implementation of changes.
Steps 1 and 2 may be intermingled and/or swapped as makes sense for our set of dependencies.

**Comment by anthonybernardi** [comment]
too vague and large scope
