### ISSUE TITLE
Teams - Make Teams Page

### ISSUE THREAD

**Issue by tom-weatherbee** [Northeastern-Electric-Racing/FinishLine#260]
## Overview

Create a space where FinishLine users can find information about individual teams, including team leads, members, current projects, and a brief summary of team activities.

## Stakeholders

Product Stakeholder: Tom Weatherbee
Engineering Stakeholder: Arnav Joshi
Reference Users: JP and Nick DePatie 

## User Story

As a current/prospective member, I want a place where I can find all the teams at NER along with what each does and which projects each is working on.

## Success Metrics

Success will be measured based on the increase over time of page views. As this feature doesn’t exist and the majority of users will likely be prospective members, we’ll set a baseline at 0.

### Feature Adoption Metrics
Feature adoption throughout the year can be measured by user traffic relative to current club membership. During recruiting periods, we can measure feature adoption by comparing the number of prospective members attending meetings to the number of Teams page accesses.

## Rollout Plan

- Deploy only the main teams page to production (ie. excluding individual team pages and ensuring there’s no link to them on the main page yet)
  - After some brief bug testing, can be rolled out to all members
- Deploy individual teams pages
- Work with team leads to fill out their team-specific summary section
  - Observe difficulties and feedback throughout this process

## Out of Scope

Discussed QOL improvements, specifically regarding expanding/contracting box indicators, which will likely be relegated to a separate epic or set of tickets in the future

## Background / Context

Currently, most of any given team’s relevant information is scattered throughout Slack, Google Drive, and Gantt charts, making it difficult for prospective members to learn about different teams, and for current members to locate what projects their team is working on. With this project, we’re trying to consolidate most of the basic information about a specific team into one place, focusing on membership, projects, and a brief summary of the team’s activities.

#### Main Teams Page
![Main Teams Page, equal size cards](https://user-images.githubusercontent.com/9142777/195727439-ff967b5d-0d72-4a5a-9715-e401827ab90a.png)
1. Individual projects link to their corresponding FinishLine project pages
2. Clicking the team name should bring the user to the Team-specific page for that team
3. All cards should be equal width but cards can vary in height to accommodate greater or fewer quantities of projects
4. Lead should be populated with the name of the team lead
5. Members should reflect the number of members in the team
6. Projects should display only projects assigned to the given team with active status

#### Team-specific Page (Member Non-Editing View)
![](https://i.imgur.com/ZCGsaqn.png)
1. Clicking on any of the red project names should take you to the corresponding project page on FinishLine
2. Projects section should display a card for every project with that is assigned to the team with active status
3. Lead should display the name of the team lead
4. Members should display the list of members currently assigned to the team

#### Team-specific Page (Team Lead Non-Editing View)
![](https://i.imgur.com/4k9nEdD.png)
1. Projects, Lead, and Members are populated in the same way described by the member non-editing view
2. Team leads on their team's page should see this version of the page
3. Clicking the pencil icon in the description box should bring them to the description editing view [Team-specific Page (Description Editing View)]
4. Clicking the pencil icon in the members box should bring them to the members editing view [Team-specific Page (Members Editing View)]

#### Team-specific Page (Members Editing View)
![image](https://user-images.githubusercontent.com/113213237/195465776-681d08cf-4e89-479f-aaa2-c483a59cffb8.png)
1. This view should only be accessible by the team lead corresponding to this page, and by ADMIN and above
2. The default view should be the current members displayed in a list of MUI chip components
3. Clicking the trash bin next to an existing member's name should remove that member from the team
4. Typing into the searchbar at the bottom of the members list should display a list of members with the search term at the beginning of their first or last name, sorted in alphabetical order by first name
    * Clicking a name in this list of members should add that member to the team
    * Clicking off the searchbar should keep the filter currently typed into it but stop displaying the filtered list of members hanging off of the bottom
9. Save button propagates changes to the database returns the user to the non-editing view, displaying a loading symbol in place of the People box while changes are being saved
10. Cancel button returns the user to the non-editing view without propagating changes to the database
11. Clicking the pencil in the description box should switch the members box to editing view without affecting the members editing view (ie. the two views should be allowed to occur simultaneously)

#### Team-specific Page (Description Editing View)
![](https://i.imgur.com/w4zZsgT.png)
1. This view should only be accessible by the team lead corresponding to this page and by website admins
2. Description section replaced with a markdown editor
    * Default text should be the existing team description
    * Cap at 300 words to discourage leads from using this in place of Confluence
      * Should physically not allow the user to type more than 300 words
    * Preview button toggles between the rendered view and the editor view of the markdown text
4. Save button saves the markdown text and returns the user to the non-editing view, displaying a loading symbol in place of the description box while the changes are being pushed to the database
5. Cancel button returns the user to the non-editing view without propagating changes to the database
6. Clicking the pencil in the members box should switch the members box to editing view without affecting the description editing view (ie. the two views should be allowed to occur simultaneously)

#### Projects Page
![image](https://user-images.githubusercontent.com/113213237/196817892-156c27c9-e356-4cef-a688-fadc3722f381.png)
<img width="878" alt="image" src="https://user-images.githubusercontent.com/113213237/196848159-a907ae40-7aee-419e-8b3a-a9a4db1bdea8.png">
1. The "Assign to my team" button should only appear for team leads and should assign the project to that team lead's team without needing a change request.
    * The button will be grayed out if the project is already assigned to a team.
2. This button will not appear to non-team-leads.
3. Clicking the team's name on the project page should bring the user to the team's individual page.
4. Apart from a difference in display order, no other details fields should change in functionality.

#### Project Creation Page
![image](https://user-images.githubusercontent.com/113213237/194990802-896be742-83b9-462c-becb-74d20b4f0c02.png)
1. The select team field should display a dropdown list of all teams when clicked
    * Clicking on a team in that list should fill the field with that team
    * This is a required field--projects cannot be created unless this field is filled
      
### Tickets

 - [x] #359 
 - [x] #360
 - [x] #362 
 - [x] #363 
 - [x] #370
 - [x] #371 
 - [x] #373

**Comment by anthonybernardi** [comment]
LETS GOOOOOOOOO
