### ISSUE TITLE
[Change Requests] - Checks for open change requests should happen on create

### ISSUE THREAD

**Issue by walker-sean** [Northeastern-Electric-Racing/FinishLine#2612]
### Observed Behavior

Currently, to avoid "merge conflicts" between change requests, we do not allow a change request to be _accepted_ if there are other opened change requests for the wbs element. This causes any changes to be impossible after 2 change requests are opened

### Expected Behavior

This should be on _create_.

### Steps to Reproduce

1. Open 2 auto-implementing change requests for a single wbs
2. try approving one

**Comment by Peyton-McKee** [comment]
completed via #2616 or #2613
