### ISSUE TITLE
[Home Page] - Create setLogo Endpoint

### ISSUE THREAD

**Issue by caiodasilva2005** [Northeastern-Electric-Racing/FinishLine#2764]
### Description

We need to create an endpoint in the organization router to set the logo of an organization in the backend. 

First, we need to update the organization model to include a `logoImageId` as an optional field in the prisma schema. Make sure to run `yarn prisma:migrate` after any changes to the schema to perform a migration.

Then we need to add a post endpoint to the organization router under the route 'organization/logo/update'  that accepts a file upload. Include unit tests and a manual test using postman to make sure everything is working correctly.

### Acceptance Criteria

- [ ] There is a new `logoImageId` field in the organization model
- [ ] There is a new post endpoint in the organization router under the route 'organization/logo/update' 
- [ ] unit tests and manual testing

### Proposed Solution

We already do something very similar in the '/images/update' post endpoint, which you can use as a reference.  For storing images on Finishline we first upload them to google drive, and then store the google file id in the database, so use the uploadFile util function to get the google file id of the image.

**Comment by Peyton-McKee** [comment]
Completed via #2834
