### ISSUE TITLE
[Home Page] - Create getFeaturedProjects Endpoint

### ISSUE THREAD

**Issue by caiodasilva2005** [Northeastern-Electric-Racing/FinishLine#2767]
### Description

We need a way to retrieve an organizations featured projects. Create an endpoint in the organization router under the route 'organization/featured-projects' which does not take in a payload, which returns a list of the featured projects of the organization.

### Acceptance Criteria

- [ ] create getFeaturedProjects endpoint under route 'organization/featured-projects' 
- [ ] Unit tests and manual testing (screenshot) is included 

### Proposed Solution

See other get endpoints in the organizations.routes.ts and model this new endpoint off other previous get endpoints.

**Comment by Peyton-McKee** [comment]
Completed #2852
