### ISSUE TITLE
[Home Page] - Create getUsersTasks Endpoint

### ISSUE THREAD

**Issue by caiodasilva2005** [Northeastern-Electric-Racing/FinishLine#2770]
### Description

We need a way to retrieve all of the tasks assigned to the current user. We need an endpoint in the task router that does not take in a payload that returns all the tasks assigned to the current user. This endpoint should be under the route '’users/tasks/:userid”

### Acceptance Criteria

- [ ] A new endpoint is added to the task router under 'users/tasks/:userid' that returns all tasks assigned to the current user
- [ ] Unit tests and screenshot of manual testing with postman

### Proposed Solution

Take a look at the other endpoints we have on Finishline and use that as a reference for this one.

**Comment by Peyton-McKee** [comment]
completed via #2833
