### ISSUE TITLE
[Stats Page] - Statistics Page Creation

### ISSUE THREAD

**Issue by martin0he** [Northeastern-Electric-Racing/FinishLine#2773]
### Description

We need to create a new page for Finishline, the statistics page.

### Acceptance Criteria

- New route and page are created
- Navigation to this page works

### Proposed Solution

- Create a new route in the app, '/statistics'
- Add a navigation button in the website's navbar that directs to the above route, and include a statistics icon (from mui icons)

### Mocks

![image](https://github.com/user-attachments/assets/2d1fe30c-ee98-4ebe-968a-92caf1edab4e)
![image](https://github.com/user-attachments/assets/024c2125-9cdc-4b6f-8c1a-4b839e8fea4a)

**Comment by Peyton-McKee** [comment]
completed via #2854
