### ISSUE TITLE
[Stats Page] - Pie Chart Component

### ISSUE THREAD

**Issue by martin0he** [Northeastern-Electric-Racing/FinishLine#2776]
### Description

We need a reusable pie chart component to display data. Using Chart.js, create a pie chart component that takes in x-axis data (the labels of each section), y-axis data (the numerical values to be displayed), time frame, width, height, and graph title.

### Acceptance Criteria

- graph displays data in pie chart format
- hovering over a section displays a tooltip with more detail
- all labels are properly formatted and sized/positioned
- width and height are responsive

### Proposed Solution

- new component file is created with suitable props

### Mocks

![image](https://github.com/user-attachments/assets/95148308-4d67-40a9-8219-33ff0fd0f4a9)
![image](https://github.com/user-attachments/assets/fa2d4673-fcd9-4212-a2b0-8172d5e5dedf)

**Comment by Peyton-McKee** [comment]
Completed via #3059
