### ISSUE TITLE
Checklist Icons

### ISSUE THREAD

**Issue by RChandler234** [Northeastern-Electric-Racing/FinishLine#279]
## IMPORTANT

This ticket doesn't require changes to package.json or yarn.lock

## Important Note

Make sure to branch from [#142-MUI-migration](https://github.com/Northeastern-Electric-Racing/FinishLine/tree/%23142-MUI-migration) and request merge back to [#142-MUI-migration](https://github.com/Northeastern-Electric-Racing/FinishLine/tree/%23142-MUI-migration) for this ticket. We are doing this work on a feature branch because it affects the whole codebase and is prone to breaking things, so a feature branch allows us to test the code without breaking develop.

## Description

Currently the Checklist component uses fortawesome icons. We want to switch that page to use Material UI Icons. Find icons on https://mui.com/material-ui/material-icons/ that match as closely as possible to the old ones on the component and replace the old ones.

## Acceptance Criteria

All the icons are replaced with material ui icons in the Checklist.tsx file. The imports for the old icons are completely removed. Functionality is unaffected.

**Comment by jonathan-chen10** [comment]
Closed by #378
