### ISSUE TITLE
[Home Page] - Guest Organization Info Component

### ISSUE THREAD

**Issue by caiodasilva2005** [Northeastern-Electric-Racing/FinishLine#2793]
### Description

On the guest home page we are going to have an intro component that will give the user some insight into the current state of their organization. We want to have a component that lists the organization’s name, general description, and useful links. 

This component should be a page block title ed the organization name.

To retrieve the data on the current orgainzation, use the useOrganization hook.

### Acceptance Criteria

- [ ] Create the organization info component in the guest homepage that includes the organization title, general description, and useful links
- [ ] Create hooks for the organization general description and useful links

### Proposed Solution

You can access the name, useful links, and description of the current organization using the useOrganization hook. 

### Mocks

![image](https://github.com/user-attachments/assets/bae9ffa5-c8bb-4d89-a928-c37658328806)

**Comment by Peyton-McKee** [comment]
Completed via #2891
