### ISSUE TITLE
[Home Page] - Featured Projects Section

### ISSUE THREAD

**Issue by caiodasilva2005** [Northeastern-Electric-Racing/FinishLine#2797]
### Description

On the guest home page, we want to have a component where the organization's featured projects are displayed. This should be in a separate page block under the Guest Intro Component., and should display a list of project cards for all featured projects

blocked by #2767 

### Acceptance Criteria

- [ ]  A component that displays the organization's featured projects is placed on the guest home page

### Proposed Solution

Add a new component to the guest home page that uses the ProjectDetailCard.tsx to display the featured projects of the organization. This new component should utilize the PageBlock Component as well. 
You can retrieve an organization’s featured projects by calling the useFeaturedProjects() hook.

### Mocks

![image](https://github.com/user-attachments/assets/e4f64e2c-e8d2-47dc-8792-394fa29720a6)

**Comment by Peyton-McKee** [comment]
Completed via #2904
