### ISSUE TITLE
[Home Page] - Team Work Packages Display 

### ISSUE THREAD

**Issue by caiodasilva2005** [Northeastern-Electric-Racing/FinishLine#2801]
### Description

We want members to be able to see all the active work packages for the teams they are in.
This section should be a page block with a vertical list of all the work packages that are currently active within the user's teams. The page block should be titled 'My Team's Work Packages' followed by the number of active work packages. Each work package should be displayed as a card, so use the WorkPackageCard component that is already created.

### Acceptance Criteria

- [ ] Create page block titled 'My Team's Work Packages ()' that shows all active work packages in a user's teams

### Proposed Solution

Use the PageBlock component and WorkPackageCard component that are already made in order to create the display.
	You can access a team’s work packages by using the useSingleTeam hook with the current users team, and accessing the work packages in each of the team’s projects.

### Mocks

![image](https://github.com/user-attachments/assets/aaa7b126-1a22-4fff-99be-ba10744454c0)

**Comment by Peyton-McKee** [comment]
Completed via #2845
