### ISSUE TITLE
[Home Page] - Selection View

### ISSUE THREAD

**Issue by caiodasilva2005** [Northeastern-Electric-Racing/FinishLine#2809]
### Description

We want leads to be able to customize their homepage to best suit their needs and facilitate project management. We want to have a page block where the title functions as a dropdown selector to select what is displayed within the pageblock.
There will be three options including: ‘In Progress Work Packages’, ‘Upcoming Work Packages’, and Overdue Work Packages’ with each title followed by the number of items in the entry.

In Progress Work Packages are work packages that are currently active in the head’s team, and can be displayed with the WorkPackageDetailCard.

Upcoming Work Packages are work packages that are currently active in the head’s team, and can be displayed with the WorkPackageDetailCard.

The Overdue Work Packages are work packages whose start date is within the next two weeks in the head’s team, and can be displayed with the WorkPackageDetailCard.

Use the utils functions getUpcomingWorkPackages, getInProgressWorkPackages, and getUpcomingWorkPackages respectively to filter out the work packages for each of the three sections of the selection.
If a section does not have an items, remove it from the selection.

### Acceptance Criteria

- [ ] new component in the leads/admins home page is created that is a page block with an option to select upcoming work packages, in progress work packages, and overdue work packages

### Proposed Solution

Use the Page Block component for to create the page block that includes the display. 
For the selector, use the mui material text field and include menu items (https://mui.com/material-ui/react-text-field/). 

Use the work package card that is already made to display all of the work packages.

You can access a team’s work packages by accessing the projects assigned to a team, which contain work packages

### Mocks

![image](https://github.com/user-attachments/assets/e8c54b0d-4408-4916-a28c-58c0434b5f39)

**Comment by Peyton-McKee** [comment]
Completed via #2888
