### ISSUE TITLE
[Home Page] - Create getLogo Endpoint

### ISSUE THREAD

**Issue by caiodasilva2005** [Northeastern-Electric-Racing/FinishLine#2831]
### Description

We need to create a get endpoint to access an organization’s logo. This endpoint should be in the organization's router under the route ‘organizations/logo’ and should not take in a payload. It should return the user’s organization logo image id. 

Be sure to include unit tests and screenshots of postman manual tests to ensure everything is working correctly 

### Acceptance Criteria

- [ ] a new endpoint is created in the organizations router under the route ‘organizations/logo’ that returns the user’s organization logo id
- [ ] unit tests and postman screenshot

### Proposed Solution

Take a look at some of the other get endpoints we have on Finishline and use it as a reference for this endpoint.

**Comment by Peyton-McKee** [comment]
Completed via #2838
