### ISSUE TITLE
[Home Page] - Separate Home Pages by Role

### ISSUE THREAD

**Issue by caiodasilva2005** [Northeastern-Electric-Racing/FinishLine#2846]
### Description

We want to tailor each home page based on a user's role. This task is to create the page layouts for each user role and have the corresponding page show up on the home page. For instance, the guest home page appears if the user is a guest, the member home page appears if the user is a member, and so on.

### Acceptance Criteria

- [ ] the corresponding homepage appears based on the current user's role

### Proposed Solution

On Home.tsx, check for the user's role and return the corresponding page based on the role.

**Comment by Peyton-McKee** [comment]
Completed via #2847
