### ISSUE TITLE
[Home Page] - setDescription Endpoint

### ISSUE THREAD

**Issue by caiodasilva2005** [Northeastern-Electric-Racing/FinishLine#2849]
### Description

We need an endpoint to set the organization description. This should be in the organization router under the route 'organizations/general-description/set'.

### Acceptance Criteria

- [ ] new endpoint is made in organization router to set organization description
- [ ] unit tests and postman screenshots

### Proposed Solution

Take a look at our other get endpoints in the organization router.

**Comment by Peyton-McKee** [comment]
Completed via #2850
