### ISSUE TITLE
[Stats Page] - Create Get Single Graph Endpoint

### ISSUE THREAD

**Issue by martin0he** [Northeastern-Electric-Racing/FinishLine#2877]
### Description

We need to create an endpoint to get a graph. This endpoint should be in the statistics router under the route ‘statistics/:graphId’ and should take in a graph id.

Be sure to include unit tests and screenshots of postman manual tests to ensure everything is working correctly.

### Acceptance Criteria

- a new endpoint is created in the statistics router under the route ‘statistics/:graphId’ that returns a single graph.
- unit tests and postman screenshot

### Proposed Solution

Take a look at some of the other get endpoints we have on Finishline and use it as a reference for this endpoint.

**Comment by Peyton-McKee** [comment]
Completed via #3062
