### ISSUE TITLE
[Stats Page] - Create Get Graph Collections

### ISSUE THREAD

**Issue by martin0he** [Northeastern-Electric-Racing/FinishLine#2883]
### Description

We need to create an endpoint to get all graph collections. This endpoint should be in the statistics router under the route ‘statistics/graphCollections’ and should not have a payload.

Be sure to include unit tests and screenshots of postman manual tests to ensure everything is working correctly.

### Acceptance Criteria

- a new endpoint is created in the statistics router under the route ‘statistics/graphCollections’ that returns all graph collections.
- unit tests and postman screenshot

### Proposed Solution

Take a look at some of the other get endpoints we have on Finishline and use it as a reference for this endpoint.

**Comment by Peyton-McKee** [comment]
completed via #3085
