### ISSUE TITLE
[Home Page] - Get Many User Tasks Endpoint

### ISSUE THREAD

**Issue by caiodasilva2005** [Northeastern-Electric-Racing/FinishLine#2897]
### Description

To facilitate getting the tasks from all users in a team, we want to make an endpoint in the user's router called getManyUserTasks which given a list of userIds returns all tasks of the each user in a list.

### Acceptance Criteria

- [ ] there is a new endpoint in the user router under the route /users/tasks/get-many

### Proposed Solution

Take a look at the getManyWorkPackages endpoint, which is very similar to this one.

**Comment by Peyton-McKee** [comment]
Completed via #2898
