### ISSUE TITLE
[Home Page] - Schema Changes For Announcements and Notifications

### ISSUE THREAD

**Issue by caiodasilva2005** [Northeastern-Electric-Racing/FinishLine#2940]
### Description

Update the Schema to include announcements and notifications.

### Acceptance Criteria

- [ ] Announcement model is made
- [ ] Notification model is made
- [ ] Users have unread notifications and announcements

### Proposed Solution

Update prisma.schema

**Comment by Peyton-McKee** [comment]
Completed Via #2941
