### ISSUE TITLE
General - Research URL query parameters design pattern

### ISSUE THREAD

**Issue by jamescd18** [Northeastern-Electric-Racing/FinishLine#31]
## Prerequisites

- [x] Northeastern-Electric-Racing/PM-Dashboard-v2#404

## Description

Research into the desired URL query parameters design pattern.

## Background

Currently, we don't have URL query parameters for data being passed to the application. 
Implementing URL query parameters would benefit multiple aspects of the application such as:
- [ ] Pre-populating forms
- [ ] Preserving filter state

This would help to save states when reloading the page and when sharing the URL with the user-selected page state.

## Proposed Solution

The solution would involve the following steps:
- [ ] Understand the purpose and benefit of URL query parameters
- [ ] Research how to implement URL query parameters on our application
- [ ] Implement URL query parameters on a specific part of the application as shown in epic Northeastern-Electric-Racing/FinishLine#30 
  - [ ] And/Or Document how to implement the URL query parameters for other people to follow 
  
Helpful Link: https://v5.reactrouter.com/web/example/query-parameters

**Comment by anthonybernardi** [comment]
ez https://github.com/Northeastern-Electric-Racing/FinishLine/pull/179
