### ISSUE TITLE
Change Requests - Allow Deletion for Unreviewed CRs

### ISSUE THREAD

**Issue by tigerhippo** [Northeastern-Electric-Racing/FinishLine#314]
### Overview

Add the ability for users / admins to delete their change requests after submitting them.

### Stakeholders

Product Stakeholder: @jamescd18 @leoRysing 
Software Stakeholder: @RChandler234 
Reference Users: Rachel Fox, Anushka Wani

### User Story

As a user, I want to be able to delete change requests after submitting them. I want this ability because I could realize that a change request is unnecessary or needs to be completely rewritten after submitting the change request. 

As an admin, I want to be able to delete change requests from my team if I see that their are issues on them. I want to do this so that I can remove faulty change requests without unnecessary middle steps.

### Success Metrics

We will measure how successful the delete feature is by counting the number of times each user clicks the 'delete' button under the Actions dropdown menu, and also the number of times each user clicks the 'Yes' button in the confirmation modal after clicking the 'delete' button.

### Background / Context

Currently, there is no way to remove Change Requests that are out of scope.

### Acceptance Criteria & Mock-ups

Frontend
![delete](https://user-images.githubusercontent.com/9142777/216208318-5b701f76-4730-42a6-8e59-e02f0cf26e0e.png)
- add a new option to the action menu in the change request page, called "Delete"
   - when clicking this item, a modal should open for confirmation
   - This menu item should be disabled for non admins, or if this change requests is not one that user has submitted
   - The delete menu item should be under a menu divider 

![delete](https://user-images.githubusercontent.com/9142777/216208804-e247df54-fa82-4160-b52a-6dc4e0784f78.png)
- For this modal;
   - Ask the user if they want to delete this cr; "Are you sure you want to delete Change Request <CRID>, attached to <Project-name> { - <work_package_name> *if exists* }"
   - Below that, inform the user; "This action cannot b eundone!"
- Block the user from confirming until they type in the change request number
- Let the user cancel if they choose 

Backend

When the user clicks the 'Yes' button in the confirmation modal, the current submitted change request should be deleted from the dashboard. Make sure of the following;
- The user must either be an admin, or the person who submitted the change request
- The change request should be unreviewed. If its reviewed, do not delete

### Tickets

 - [x] #825 
 - [x] #826

**Comment by anthonybernardi** [comment]
yahoooooo
