### ISSUE TITLE
Projects - Add URL query parameters to projects table page for filtering

### ISSUE THREAD

**Issue by jamescd18** [Northeastern-Electric-Racing/FinishLine#32]
## Prerequisite

- [ ] Northeastern-Electric-Racing/FinishLine#31 

## Description

Add URL Query parameters to the project's table page for filtering. The main benefit of this is pre-populating this page.

## Business Logic

The following URL query parameters should be supported to fill in their corresponding fields in the page;
- [ ] CRID

## Proposed Solution

# !!Actually we might hold off on this because of mui!!
see this pr: https://github.com/Northeastern-Electric-Racing/FinishLine/pull/179

**Comment by anthonybernardi** [comment]
not relevant with table change to mui
