### ISSUE TITLE
Projects - Allow Deletion of Projects and Work Packages

### ISSUE THREAD

**Issue by leoRysing** [Northeastern-Electric-Racing/FinishLine#334]
### Overview

Add a new action for admins to delete work packages and projects directly from their pages.

### Stakeholders

Product Stakeholder: @leoRysing 
Software Stakeholder: @RChandler234 
Reference Users: James Chang-Davidson, Matyas Spunberg

### User Story

As an admin, I want to delete projects / work packages when mistakes get made, for example attached to the wrong car or project. I want to be able to do this when problems come up, so that I do not have to take my issues to the Software Team.

### Success Metrics

Success of this feature will be measured on the time it takes to delete a WP/project.

Baseline: 5-15 minutes

### Rollout Plan

- Deployment of features to production: Roll out this feature for heads of the club, allowing permission for them to delete work packages and projects
- Work with heads
  - Make changes or bug fixes if issues pop up
- No broad club rollout, but consider allowing leads to delete projects or work packages, depending on the need

### Background / Context

Currently, when issues like this arrises, we get a request in #software_product_requests to fix this data, and James has to go in and manually manipulate the data. We want to remove some of this need from his shoulders, so we want to enable admins (heads) to be able to delete their own projects and work packages when needed.

### For a Work Package
![Work Package Page - New Actions](https://user-images.githubusercontent.com/9142777/216100545-b7eead55-fcec-49e0-898c-0451da68c39d.png)

- The option to delete a work package will fit into the actions menu
- This item will be present below a [divider in the menu dropdown](https://mui.com/material-ui/react-menu/#icon-menu)
- For non admins, the delete action will be disabled

![Screenshot 2023-02-01 at 11 14 21 AM](https://user-images.githubusercontent.com/9142777/216099534-a5d3d303-8e09-4d04-9408-bdd8e9105035.png)

#### Confirmation Page - Work Package
![Work Package Page](https://user-images.githubusercontent.com/9142777/215571708-62cd23d3-d8c8-45b4-8a95-bec4bc889121.png)
- Upon clicking the delete button, open a confirmation modal
- Top line of the modal should say; "Are you sure you want to delete this work package?"
   - Below that; "<WBS_num> <work_package_name> of project <Project WBS Num> <project_name> will be deleted."
   - Under that, display the number of change requests that will also be deleted; "<number> change requests will also be deleted.
   - After a small white space, let the user know that; "This action cannot be undone!"
- Block the user from being to click confirm until they type a confirmation phrase; this will be the name of the work package
- At the bottom of the modal; give the option to delete, or cancel the deletion:

#### Confirmation page - Project
![New Project Deletion modal](https://user-images.githubusercontent.com/9142777/215571788-60ca2fe0-33d7-4ee5-936b-13eed0dd0cc3.png)
- Upon clicking the delete button, open a confirmation modal
- Top line of the modal should say; "Are you sure you want to delete project <project_WBS_Num> - <project_name>?"
   - Below this, let the user know how many work packages are associated with the project
   - Also, display the number of change requests that will also be deleted; "<number> change requests will also be deleted.
   - Below that, add that all info associated with the project will be deleted.
   - After a small white space, let the user know that; "This action cannot be undone!"
- Block the user from being to click confirm until they type a confirmation phrase; this will be the name of the project
- At the bottom of the modal; give the option to delete, or cancel the deletion:

### Tickets

 - [x] #418
 - [x] #419 
 - [x] #420 
 - [x] #421 
 - [x] #422

**Comment by anthonybernardi** [comment]
yurrrrrrrrrrrrrrr
