### ISSUE TITLE
Work Packages - Abstract Util Functions Into One Builder Function

### ISSUE THREAD

**Issue by jpwaves** [Northeastern-Electric-Racing/FinishLine#36]
## Description

Abstract the code in the `CreateWPFormView` that is related to the utility functions.

## Prerequisites
- [x] Northeastern-Electric-Racing/FinishLine#37 

## Current State

Within the `CreateWPFormView`, we currently hardcode the `add`, `update`, and `remove` utility functions that are passed down to `EditableTextInputList`. 

## Desired Changes

If you look at the code snippet below, you can see similarities with all of the utility functions used for dependencies, expected activities, and deliverables. 

Here is the code that we are trying to abstract:
https://github.com/Northeastern-Electric-Racing/PM-Dashboard-v2/blob/3e46727a554bb5882a944ca5bf4e3d113b9f9a9a/src/components/projects/create-wp-form/create-wp-form.tsx#L23-L75

## Proposed Solution

This is just like a fundies 1 abstraction problem. Review the three objects in the code snippet above and circle the parts that are different. Use that as your starting point for figuring out how to abstract creating those 3 objects.

We can reduce and abstract out the code by writing a single function that takes in `index`, `val`, the state, and the associated `setState` method (type `(val: any) => void`), and returns an object that uses the new interface created in Northeastern-Electric-Racing/FinishLine#37.

Make sure to adjust any related test files to ensure that all tests still pass after this change.

**Comment by anthonybernardi** [comment]
we're going to make this form use react hook forms so this ticket is not needed
