### ISSUE TITLE
Documentation - Onboarding node version

### ISSUE THREAD

**Issue by acd124** [Northeastern-Electric-Racing/FinishLine#38]
## Description

Users have been installing the latest node version during onboarding which results in set up issues.

## Desired Changes

Specify the proper version of node, v14.19.0, users should install when setting up the environment in the onboarding steps.

## Proposed Solutions

Windows: npm install -g node@14.19.0
Mac: brew link node@14.19.0

## Screenshots (as needed)

<img width="326" alt="Screen Shot 2022-02-16 at 6 44 38 PM" src="https://user-images.githubusercontent.com/51572473/154376408-5b68c54c-4a42-4731-967b-2cbc18d274e7.png">

**Comment by anthonybernardi** [comment]
arnav will take care of this with his onboarding
