### ISSUE TITLE
Backend - Dont send WBS objects in errors

### ISSUE THREAD

**Issue by anthonybernardi** [Northeastern-Electric-Racing/FinishLine#380]
### Description

we send some error messages saying like `project with wbs 1.1.0 not found` but we send the wbs number object which renders as `project with [Object object] not found` or whatever.

### Acceptance Criteria

make a util function that turns a wbs into a string (or it might already exist?)

put it in shared

replace the few instances of this... if you search all the controller files for all the 404 errors you should find them. i think there's 2 or 3

**Comment by JasperTheDog** [comment]
This is no longer an issue :)
