### ISSUE TITLE
Documentation - Create Documentation for Project Structure

### ISSUE THREAD

**Issue by acd124** [Northeastern-Electric-Racing/FinishLine#39]
## Description

There is not currently any documentation detailing the structure of the entire codebase. An overview would simplify onboarding and help developers find information more quickly.

## Desired Changes

Establish a centralized source of information for how to navigate the folder structures for the backend and frontend.

## Proposed Solution

Go through [the Zoom recording](https://northeastern.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=a6506066-5f6b-4f15-b6cc-ae41015414e2) of James' going through the codebase to start.

**Comment by anthonybernardi** [comment]
we are doing onboarding stuff
