### ISSUE TITLE
Repository - Resolve High Package Vulnerabilities

### ISSUE THREAD

**Issue by kevinyu328** [Northeastern-Electric-Racing/FinishLine#42]
### Background

While development can continue to move forward package vulnerabilities present, these vulnerabilities should be addressed as they may pose security threats in the long run. High level vulnerabilities pose a security threat and should be addressed after the critical vulnerabilities have been resolved. We currently have 18 high level vulnerabilities that need to be resolved.

### Prerequisites
- [ ] Northeastern-Electric-Racing/FinishLine#11 

### Proposed Solution
- [ ] Run `npm audit` and view audit report
- [ ] Fix the 18 high level critical level vulnerabilities either automatically or manually according to suggestions from the adult report
- [ ] Ensure that fix does not break current build
- [ ] This site could be a helpful start: https://www.whitesourcesoftware.com/free-developer-tools/blog/npm-audit/

### Screenshots 
<img width="390" alt="Screen Shot 2021-12-27 at 7 58 27 PM" src="https://user-images.githubusercontent.com/51571627/147526455-a9bf4a5e-a1ad-470e-a2db-73c8cd63c6d9.png">

**Comment by Ari-S-123** [comment]
![image](https://user-images.githubusercontent.com/80832201/184198222-35c207c5-fe58-4527-8696-d8b679e81a1f.png)
