### ISSUE TITLE
Admin Tools - Create Delete Projects/Work Packages Block

### ISSUE THREAD

**Issue by joshiarnav** [Northeastern-Electric-Racing/FinishLine#420]
### Description

Blocked by #293, somewhat blocked by #418 and #419

Create a new block on the admin tools page titled Delete Faulty Projects and Work packages to do the namesake for admins and app_admins.

### Acceptance Criteria

- Title should be Delete Faulty Projects and Work packages
- Add a short description of the task at hand - "Delete faulty projects or work packages. First search a project if you want to do delete a project, or follow up with a work package search if you want to delete a work package."

Project Deletion details

- Have a search bar to select projects
- Select projects by name, or by WBS number
- Suggest projects that match in a dropdown
- Display projects with the format {WBS Number} - Project Name
- Once a project is selected, give the option to delete (otherwise should be grayed out)

Work Package Deletion details

- Have a search bar to select work packages
- Select work packages by name, or by WBS number
- Suggest work packages that match in a dropdown
- Display work packages with the format {WBS Number} - Work Package Name
- Once a work packages is selected, give the option to delete

### Proposed Solution

Go to the Admin Tools page and mimic the existing page block to create a new page block.

For the autocompleting search bar, utilize the [React Autocomplete](https://mui.com/material-ui/react-autocomplete/) component.

### Mocks

![](https://user-images.githubusercontent.com/9142777/196552892-6bd59959-cb28-4e3e-9e4a-d4c2c6692c52.png)

![](https://user-images.githubusercontent.com/9142777/196552928-b4154aac-6339-43ab-97bb-692e04d5c83b.png)

![](https://user-images.githubusercontent.com/9142777/196552944-c07cedf6-6e17-44c3-8988-37934992545d.png)

**Comment by anthonybernardi** [comment]
not doing the page block anymore
