### ISSUE TITLE
Repository - Resolve Moderate Package Vulnerabilities

### ISSUE THREAD

**Issue by kevinyu328** [Northeastern-Electric-Racing/FinishLine#43]
### Background
While development can continue to move forward package vulnerabilities present, these vulnerabilities should be addressed as they may pose security threats in the long run. Moderate vulnerabilities pose some security threat and should be addressed after the critical and high level vulnerabilities have been resolved. We currently have 22 moderate vulnerabilities that need to be resolved.

### Prerequisites
 - [ ] Northeastern-Electric-Racing/FinishLine#11
 - [ ] Northeastern-Electric-Racing/PM-Dashboard-v2#538

### Proposed Solution
- [ ] Run `npm audit` and view audit report
- [ ] Fix the 22 moderate level vulnerabilities either automatically or manually according to suggestions from the adult report
- [ ] Ensure that fix does not break current build
- [ ] This site could be a helpful start: https://www.whitesourcesoftware.com/free-developer-tools/blog/npm-audit/

### Screenshots
<img width="390" alt="Screen Shot 2021-12-27 at 7 58 27 PM" src="https://user-images.githubusercontent.com/51571627/147526455-a9bf4a5e-a1ad-470e-a2db-73c8cd63c6d9.png">

**Comment by Ari-S-123** [comment]
![image](https://user-images.githubusercontent.com/80832201/184198241-212d3b75-e73c-4740-b777-10a436d814da.png)
