### ISSUE TITLE
Change Requests - New Overview Page

### ISSUE THREAD

**Issue by leoRysing** [Northeastern-Electric-Racing/FinishLine#432]
### Overview

Create a new default view for the change requests page, which is a more personalized view for the user.

### Stakeholders

*Product Stakeholders:* @jamescd18 , @leoRysing 
*Engineering Stakeholders:* @RChandler234 
*Reference Users:* Sofia Varner

### User Stories

As a Head, I want to have a more streamlined personal view of change requests, so that I can access change requests that I need to look at or work on easily, without needing to scroll through all change requests across the page.

As a Lead, I want to have more easily see change requests I have created, so that I can easily access them as soon as I go to the change requests page, instead of needing to see this from a massive table.

TODO; combine these, maybe work them together

### Success Metrics

Before and After metrics; frequency / rate that Heads and PLs check the main change request page. Frequency defined by page views, over the period of a week.

Baseline; [check in with Emma, Sofia, etc, get an average]

Feature Adoption Metrics; frequency / rate that Heads and PLs stay on the All Change Requests Page
Success; when the comparison metric is decreased down to X% [X being 0-25%], in other words, Heads and PLs only need to check in on the all change requests page less than 25% of the time, based on the frequency they check the complete change requests page in the current version of FinishLine

### Rollout plan

- Once features are created and deployed, release it in stages;
  - Release to Heads, confirm working
  - Release to Project Leads, confirm working
- Throughout the process, address bugs that show up, since people may have questions on the new format

### Background

Currently, the change requests page is a massive table that displays all the change requests. This is not the best flow for users, because there is too much information, filtering is not ideal, and they have to memorize change request IDs.

### Acceptance Criteria and Mocks

Current mockups can be found on [figma](https://www.figma.com/file/qmXuySSwfiD942HwmSSEMe/NERPM-Desktop?node-id=1732%3A2754&t=rKGFNHrCeOok8cE9-1)

![New Change Request - My CRs  Leads](https://user-images.githubusercontent.com/9142777/225479726-7cec92f4-f399-4bd0-8454-0db25dfccd78.png)

- Create a new tab view on the change requests page
- The old change request view should still be accessible, under a tab called "All Change Requests"
- The new page should be the landing page for change requests, and should be called "Overview"
- The page should be made of three main page blocks
- Above the tabs, a big header should label the page as Change Requests

*Card mockup sections*

![Screenshot 2023-02-24 at 4 39 02 PM](https://user-images.githubusercontent.com/9142777/221298282-d7c95dc1-bf87-4201-af2e-a691c13e7424.png)

- Cards on this page will follow a standard format; 
- They will share the following details
  - In [NER RED], have the CRID
  - In [NER RED], [Heading size font], display <CRID> | <WBS#> - <WBS-Name>
  - Below this, have the submissions section, which will have a label of "Submitted:", and display the submitter name and date to the right of this
  - Have a pill section to label the status, as one of ACTIVATION, DEFINITION_CHANGE, STAGE_GATE, ISSUE, or OTHER
  - Since change requests come in a variety of types, cards will reflect this

Standard change request card
- Standard change requests will display a preview of their what, displaying up to 2 lines
- They will also show a summary of their change requests, mainly in number and in status
- Have a Header (header 3 size) to label the section as proposed solutions
- Below this have a smart list, that will display how many proposed solutions have No Status. how many are Denied, and if it is approved, that there is 1 approved change request

Stage Gate Change Request
- Stage gate change requests will display their leftover budget, and if the work package was completed, as a yes or no value
- leftover budget and WP completion should be in one line, with the leftover budget on the left

Activation Change Request
- In one line, the card will show the Project Lead and the start date
- Below this, will be the Project Manager
- For each of these, have a bolded identifier, with an adjacent text item displaying the relevant value

![New Change Request - My CRs](https://user-images.githubusercontent.com/9142777/225479771-12220f9d-75b7-48d2-a8f5-c826f9c3c12e.png)

- When a head views the My Change Requests tab, they should see the following row at the top of their page;
- It should be a page block, with the section title "To Review"
- To the right of the section title, in a smaller font, display how many Change Requests need to be reviewed
    - <# in this section> Left,
- It will be dedicated to the following change request slice;
    -  All change requests with a WBS number associated with my team or a project/work package that I am a lead or manager off, which have not been approved yet
- This section should consist of a scrollable section, similar to the upcoming deadlines section
- Change requests should be ordered in descending chronological order, left to right 

- Both heads and leads should be able to see this page block
- It should be a page block, with the section title "My Contributions"
- It should be dedicated to the following slice;
    - All change requests I have created, that have not been reviewed yet, or have been denied.
- This section should consist of a scrollable section, similar to the upcoming deadlines section
    - Only the user's unapproved change requests should go here
    - Change requests should be ordered in descending chronological order, left to right

*Bottom section - My approved Change Requests
![New Change Request - My CRs Expanded](https://user-images.githubusercontent.com/9142777/225479842-1d394873-140e-4b5e-8032-cd344bae1428.png)

- All users should be able to see this section
- This section will be collapsed by default
- It should be a page block with the name "My Approved Change Requests"
    - Change Requests the user has made that have been approved will stay populated in this grid for up to 5 days
    - Entries will be in chronological order; in other words items with the most urgent deadlines (most recently approved) will appear at the front, while newer change requests will be populated at the back.
    - For leads, it should be all change requests that they have submitted or are a project lead on that have been approved

### Tickets
- [x] #1038
- [x] #1040

**Comment by RChandler234** [comment]
LGTM
