### ISSUE TITLE
Transition to MUI - New font

### ISSUE THREAD

**Issue by anthonybernardi** [Northeastern-Electric-Racing/FinishLine#443]
### Description

we have new style guidelines as a club https://docs.google.com/document/d/1bV-TGorNeGbn7BhrwP9_nhSb_qmfs5wxJeJY5AfekDo/edit

so now we can change the font (thank the lord)

### Acceptance Criteria

change the default font to be lato for everything except h1, h2, h3, h4, h5, h6 which should be barlo

### Proposed Solution

idrk where this is in the mui stuff but probably with the themes. might need to google it

**Comment by jonathan-chen10** [comment]
Closed by #461
