### ISSUE TITLE
General - Research libraries for redesigning our form architecture

### ISSUE THREAD

**Issue by jpwaves** [Northeastern-Electric-Racing/FinishLine#45]
### Desired Changes

As of now, we currently use states and pass those down to the view components to get the data from our forms and then send them back up to our container component to do business logic with them/pass the data to our custom react hooks. We also manually do form validation, and our current validation is the bare minimum at best. We want to utilize existing libraries that provide the tools and architecture that would allow us to create flexible forms with proper validation and are easy to build. Some potential options we have right now are [Formik](https://formik.org/docs/overview) and [React Hook Forms](https://react-hook-form.com/).

**Comment by anthonybernardi** [comment]
it works so this ticket is done
