### ISSUE TITLE
Projects - New Overview Page

### ISSUE THREAD

**Issue by tigerhippo** [Northeastern-Electric-Racing/FinishLine#459]
### Overview

Add the ability for leads to see the projects for their team on a personalized projects page. Add the ability for heads to see the projects for all teams under their control on this same personalized projects page. Additionally, make the current general projects page easier to navigate.

### Stakeholders

Product Stakeholder: @leoRysing, @James
Software Stakeholder: @RChandler234 
Reference Users: @anushkan-wani, Jakob Rauen, Joseph Shneyderman

### User Story

As a lead, I want to be able to view the projects directly connected to me. I want this ability because I want to keep track of them, need to see their status, and also want to view their work package information. I rarely need to see information for other projects besides my own.

As a head, I want to be able to view both the projects that are directly connected to me, and the projects with WBS numbers connected to my team. I want this ability because I wish to both keep track of my own projects and manage projects across leads.

### Success Metrics

We will measure success by seeing how many times the personalized home page is visited by each lead/head. We will also see how many times the general project page is visited and the number of searches made on this page.

### Rollout Plan

First, the new layout will be released to heads to see if they like it or if there are any changes that need to be made, and then we will release to leads.

### Out of Scope

Will fill this in

### Background / Context

Currently, the projects page shows all projects being worked on (most of them unrelated to the lead/head that is viewing them) and is also a bit difficult to navigate. There is also a table that shows all the projects with a way to filter them by car number, status, project lead, and project manager. This is not a great way to search for information for a specific project quickly and efficiently.

### Acceptance Criteria & Mock-ups

Frontend

![New Projects Page (1)](https://user-images.githubusercontent.com/9142777/223573683-165e57b1-ab5e-481d-ad24-04b8a2e7c35b.png)

- When a lead/head clicks on the 'Projects' button, direct them to a new projects page view
- This project view should be labeled as "Overview", with an alternate one that is labeled "All Projects" which redirects to the old projects view is currently on this page. 
- The personalized projects page should have a breadcrumbs displaying Home/Projects/Personalized Projects in the top left corner underneath the tabs. 
- Label the page in the top right as the Projects page
- The page should contain one section, which is a grid of project cards

##### Project Card

![One WP](https://user-images.githubusercontent.com/9142777/223573822-c9f8f39f-77f8-4b8f-be73-9c1e8d55b121.png)
![Two WP](https://user-images.githubusercontent.com/9142777/223573843-c3a83525-81ec-4180-a55d-98d177af9dfc.png)

- The card will have the project wbs number and name in the top left corner
- In the top right, a star icon will showcase the new favoriting functionality 
   - All projects can be favorited / unfavorited. When on the overview page, the icon will allow a shorthand way to do this
   - The icon will be filled in when a project is favorited, and will just be an outline when it is not
- Below this, display the timeline information (how many weeks the project has till its expected end date, then the budget information for the project
- Below this display the confluence link with a little icon
- Below this, display the active work package(s)
   - Most projects will only have one work package active at a time. In this case, just follow the first picture
   - In rare cases, a project can have two work packages active at the same time. In this case, display the most urgent one at the top, and divide the two with a line
   - Work packages will have timeline and budget information, just like the project
  
##### Grid
- The grid will be a flex wrap grid
- Sort the grid in the following manner; first display favorited projects, then projects the user is a lead / manager of, then projects on their subteam
- Any projects can be favorited from their individual project page, described later
- When a project in the overview is favorited, it will be auto moved to the favorites section

##### Favoriting / Unfavoriting from project

![Screenshot 2023-03-07 at 6 23 21 PM](https://user-images.githubusercontent.com/9142777/223578102-df7176ab-b099-45b1-9915-54078ba3df29.png)
![Screenshot 2023-03-07 at 6 23 30 PM](https://user-images.githubusercontent.com/9142777/223578111-76aa96e1-bbd1-420f-a661-3d9c113224df.png)
- Every project can be favorited, because a new option is present in the actions menu
- When a project is not currently favorited, show the option; "Favorite", with the same favorite icon as in the cards
- When a project is favorited, show the option; "Unfavorite", with the same unfavorite icon as in the cards

### Tickets

 - [x] #988
 - [x] #989
 - [x] #990
 - [x] #991
 - [x] #992

**Comment by RChandler234** [comment]
Done in release 3 🔥
