### ISSUE TITLE
MUI - Visual Cleanup

### ISSUE THREAD

**Issue by anthonybernardi** [Northeastern-Electric-Racing/FinishLine#469]
## Description

before we release the MUI branch, we want to clean up some of the uglier MUI things that will be easy enough to do.

## Acceptance Criteria

- address this doc https://docs.google.com/document/d/1rnsJJaHi7mdU2AJaDAKvL4rw3jZ_NSOkIC35Ijhfklk/edit
- idk if this is in the doc or not but i hate that all the links are purple, they should be the primary NER color

## Proposed Solution
- [x] Light Mode Text Color should be NER dark gray instead of black
- [x] Adjust ner logo in top left to have a bit more spacing on top/bottom, so it looks a little more consistent/ cleaner (see develop logo placement for reference)
- [x] Make player icon in top right bigger
- [x] Make breadcrumbs a little closer together (see develop)
- [x] Outline of trickster mode switch not visible in light mode
- [x]  Make outlines of cards on home page more distinct
- [x] Enable outlines on date range and timeline status in light mode by default
- [x] Space out useful links a bit more
- [x] See if you can make the entirety of Next # Days clickable
- [x] In cards on homepage, make subheaders bold (e.g. End Date, Progress,Engineering Lead, etc.).
- [x] See what we can do with the filter to make it look better (e.g. extend lines down from filters through options) (Projects)
- [x] Project Detail Page: bring info closer to headers and bold headers to make distinct in project details
- [x] Make sure change request link (under changes) is red (not blue) in light mode
- [x] Make less space at bottom of gantt chart
- [x] Add new risk should look like the NER Button (red)/ use the contained button styling.)
- [x] Remove shadow on convert to CR button in risk log
- [x] Make outline between work packages more distinct (light more and dark mode)
- [x] Pills are misaligned with the weeks in work packages - make them smaller so they fit in line
- [x] Project Edit Form: inputs should be outlined by default
- [x] Make delete button look like other delete buttons (red with white trashcan) 
- [x] Submit button should be on right, cancel on left
- [x] Work Package Detail Page: bring info closer to headers and bold headers to make distinct in project details
- [x] Make sure change request link (under changes) is red (not blue) in light mode
- [x] Change Requests Page: See how left aligning the items in each column looks, keep whichever way looks better
- [x] Change Request Detail Page: Make sure change request link next to WBSNum, and under implemented changes is red not blue
- [x] Proposed Solution: Description and Scope impact should be next to each other/ have more space, and budget/timeline impact should be next to each other and have less space
- [x] Info Page: vertical spacing of links isn’t consistent (fix spacing on this page in general)
- [x] Dark Mode Specific: make background dark gray instead of black
- [x] Teams: make sizing more consistent if projects line wraps around (looks weird rn, I feel like the cards should move on to a new line/ extend horizontally rather than changing vertical size when info gets too big)
- [x] Light Mode: Increase contrast between PageBlock/Box elements and Background
- [x] version number? (bottom left of sidebar)
- [x] text inputs should all be outlined correctly by default 💀 
- [x] use form labels instead of just typographies on inputs (make sure for select menus the form labels are supposed to kinda overlap with the outline of the dropdown and this should help reduce the overall vertical height)
- [x] make scrollbars on home page less ugly
- [x] make collapsed page blocks take up less vertical space below the header
- [x] interactive elements placed in the header right of a page block (see home page) should not increase the vertical height of the page block header. using form labels properly should help with this, but if necessary, make the interactive elements be a smaller size
- [x] Fix home page date picker and select labels
- [x] fix Teams cards to be consistent sizes, most likely by simply truncating too many projects

**Comment by RChandler234** [comment]
![image](https://user-images.githubusercontent.com/29521172/211722962-a5bddd1f-fbd7-474c-b90c-b7964aacd630.png)
