### ISSUE TITLE
Object validation

### ISSUE THREAD

**Issue by jnnhng** [Northeastern-Electric-Racing/FinishLine#47]
## Description

Return a more specific string when an object is not valid to help us understand why the object is not valid.

## Background

Currently, when an object is not valid, there is a string that tells us the object is invalid.

## Desired Behavior

We want the output to detail why the object is invalid so that it is easier to tackle the issue. 

## Proposed Solution

**Comment by anthonybernardi** [comment]
express validator sends pretty good messages
