### ISSUE TITLE
[DevOps] - Add GitHub Workflows for Stale Tickets

### ISSUE THREAD

**Issue by z-roth** [Northeastern-Electric-Racing/FinishLine#481]
### Current Features

Currently, we have no system for marking tickets that have gone stale.

### Desired Additional Features

Develop a system for marking tickets as stale after not having a PR opened after a certain amount of time. This way we can see tickets that have been assigned to developers but have not had any done work to them after a certain amount of time (mainly be developers that have dropped)

**Comment by jonathan-chen10** [comment]
Testing in a personal repo: see https://github.com/jonathan-chen10/react-stale-workflow-test/tree/main/proposed-workflows/update-state

**Comment by jonathan-chen10** [comment]
Can't figure out how to fit specs. Just use https://github.com/marketplace/actions/close-stale-issues probably, with the following settings,

- days-before-pr-stale = -1
- days-before-close = -1
- exempt-issue-labels = ['epic']
- maybe some others idk

Might run into rate limits if the cron job makes one request per issue
