### ISSUE TITLE
General - Look into `json-schema-to-ts` alternatives

### ISSUE THREAD

**Issue by jpwaves** [Northeastern-Electric-Racing/FinishLine#49]
### Spike Type

Technical

### Goal

With the integration of `react-hook-forms` going nicely right now with the development on Northeastern-Electric-Racing/FinishLine#46, we have begun using the resolvers from `@hookform/resolvers`, which apply validation schemas from external libraries like `yup` and `joi` to data submitted by the form. Unfortunately, `json-schema-to-ts` isn't one of the validation schema libraries that is compatible with `@hookform/resolvers`. We want to try to see if there is an alternative to `json-schema-to-ts` that does the same schema validation while also being compatible with these resolvers while also being compatible with our `middy` backend functions.

### Reason for Spike

Ideally, if we find an alternative validation schema that is compatible with these resolvers, we'll be able to reduce duplication and also lower the number of dependencies our codebase has - we want to be able to use one schema library that can work with both our front-end form validation and backend `middy` functions.

### Additional notes

First, look into whether or not there is a pattern with using resolvers for our backend. Once that is found and confirmed, then look into the other alternative validation schema packages that `@hookform/resolvers` is compatible with (recommend starting with `yup` as we are currently using that for our forms)

**Comment by anthonybernardi** [comment]
gonna make this ticket again but better...
