### ISSUE TITLE
Finance - Make Reimbursements Dashboard

### ISSUE THREAD

**Issue by tom-weatherbee** [Northeastern-Electric-Racing/FinishLine#493]
### Overview

Create a space where users can submit and track reimbursement requests from SABO request through to reimbursement receipt.

### Stakeholders

Product Stakeholder: Thomas Weatherbee
Software Stakeholder: Reid Chandler, Peyton McKee
Reference Users: Brody Perlman

### User Story

As a NER member, I want a place to submit and track my reimbursement requests, so that I can submit a form once instead of the SABO form once and NER reimbursement form twice. As a Finance team member, I want an easy way to monitor reimbursement requests, so that I can keep track of club-wide reimbursement statuses without trying to coordinate between SABO request emails, NER reimbursement form responses, advisor emails, and club member self-reports of filled reimbursements on Slack.

### Rollout Plan
- Deploy everything
- Investigate extension that fills out SABO form for you (but the user still has to manually submit themselves)

### Out of Scope

This epic does not include linking to project BOMs, sponsorship tracking, budget formulation, and comprehensive vendor management.

### Background / Context

Currently, the process for reimbursements is divided into two parallel processes--
- User must fill out a form on the SABO website to get reimbursed
- User must fill out a form created by NER to allow the finance team to track reimbursements
    - NER form asks about delivery status and reimbursement status when those may not be known at the time of filling it out, especially since it's meant to be filled out right after the SABO form
    - NER form has essentially the same information as the SABO form, waste of user's time
    - Data quality from NER form isn't great

### Acceptance Criteria & Mock-ups
NOTE: These are not pixel perfect by any means and are just meant to be rough guidelines for how to lay things out. Please use the existing website component to create things like tables, text, etc.

#### Main Reimbursement Dashboard (Non-Finance View)
![image](https://user-images.githubusercontent.com/113213237/227027698-29f28885-14be-4abf-9585-b97ea520d5ac.png)
1. Both tables default sort by date descending (most recent first)
2. Clicking the "Report Refund" button should open the New Account Credit Overlay
3. Clicking the "Create Reimbursement Request" button should take the user to the New Reimbursement Request Form
   - This button should only be not grayed out for leads+
4. If a user is on the "My X" tab in either section, the table should show only the user's requests/refunds. If the user is in the "All Club X" section, the table should show all of requests/refunds for the club. Refunds and SABO requests should be independent of each other (eg. the user can be on "My Refunds" and "All Club Requests" at the same time)
5. Possible Statuses are "Pending Finance", "Pending Advisor", and "Approved"
 
#### New Account Credit Overlay
![image](https://user-images.githubusercontent.com/113213237/227013472-43e0e581-a48d-464d-8dbe-6649a281bfe3.png)
1. Clicking "Cancel" should close the overlay and return to the Main Reimbursements Dashboard view
2. Clicking "Submit" should propagate the information to the database and return the user to the Main Reimbursements Dashboard view
3. $ Box should only allow numbers

#### New Reimbursement Request Form
![image](https://user-images.githubusercontent.com/113213237/227031679-bcc6440d-52fd-4503-828b-6e000f884c73.png)
![image](https://user-images.githubusercontent.com/113213237/227031781-a242246e-9806-4463-ba91-9750b24a8fc7.png)
1. Recipient Profile should allow the user to search through the list of users with registered profiles (ie. they've added their address + phone # to their profile)
2. Purchased From should allow the user to search through the list of registered vendors (set up on the admin tools page)
3. Enter WBS # should allow the user to search through projects/work packages
4. Expense type should have options: "Subscriptions", "General Supplies/Small Tools", "Advertising Agencies", "Memberships and Dues", and "Equipment >1,500 (Non-Computer)"
   - Only accounts marked approved in the admin tools table should appear here
5. Date of Expense should bring up an MUI Date Picker when clicked
7. Product Table
   - Entering a WBS number in the last row should create a new empty WBS # row
   - Clicking the + chip should create a default chip allowing the user to enter the product name and cost as shown in the 2.1.3 row (when users go to submit, remove all empty chips -- if a chip is missing either name or price, do not allow user to submit and notify them that a chip is missing information)
   - Clicking the trash can in a chip should delete the chip
8. Clicking submit should propagate all information to the database, default the request to "Pending Finance" status, and bring the user to the "View Reimbursement Request" page corresponding to this reimbursement request instead of the plaintext helper
9. Clicking "Cancel" should return the user to the Main Reimbursements Dashboard view without doing anything else

#### View Reimbursement Request
![image](https://user-images.githubusercontent.com/113213237/227026952-8d6b000a-ff08-4aff-8ff0-2751bdbfb631.png)
1. All fields here correspond to the fields of the same name in the "New SABO Request" form
   - "Submitted By" is the name of the person who submitted the form
   - "Confirm Total Cost" just becomes "Total Cost"
   - Receipts shows the uploaded photos rather than just the file names
2. Actions has the option "Edit", greyed out if the user is not the original submitter of the request or if the request has already been approved by the Finance Team. Clicking "Edit" brings the user to the "Edit Reimbursement Request" view
3. "Delete" is grayed out if the user is not the original submitter or if the request has already been approved by the finance team
4. If the request doesn't have a number, list the Recipient Name and Date of Expense in the header instead.
5. Clicking "Mark Delivered" should save today's date to that reimbursement request as the delivery date and display it in the "Date Delivered" column.
6. Clicking "Add SABO #" button should open an overlay similar to the "New Account Credit" overlay, just labeled "Add SABO #" instead, without the $ sign.

#### Edit SABO Request
![image](https://user-images.githubusercontent.com/113213237/227016376-4330208f-6742-41f5-bba3-f54a7e829250.png)
1. Essentially the same as "New SABO Request", please reference that section
2. Submit has been changed to "Save"

#### User Profile Setup
![image](https://user-images.githubusercontent.com/113213237/236633049-d1c8b77c-3c4f-4226-af22-e97db4eecfe2.png)
1. Add fields for Address, Phone #, and NUID to user settings, in the same style as the slack id.

### _Finance Team Config (Admin Tools)_
![image](https://user-images.githubusercontent.com/113213237/227030207-a07b470c-4f8a-4919-9019-f03714e83e90.png)
1. The "Account Code" column in the "Account Codes" table should be editable
2. In the new/edit reimbursement request form, only account codes marked allowed should appear
4. Only vendors in the "Registered Vendors" list should appear in the Purchased From field in the new/edit reimbursement request form

#### Main Reimbursement Dashboard (Finance View)
![image](https://user-images.githubusercontent.com/113213237/227016430-fc94c694-bc6a-4d20-9319-deb0f05f3bcf.png)
1. The two [FT] options should be grayed out unless viewed by the finance team
5. Clicking the "Pending Advisor List" button should open the "Pending Advisor List" popup
6. Clicking the "Generate All Receipts" button should open the "Generate All Receipts" popup

#### Generate All Receipts
![image](https://user-images.githubusercontent.com/113213237/227018997-25399dbf-baa8-4781-ae8b-a2c963fd14f6.png)
1. Both start and end dates should open a Date Picker MUI Component
2. Clicking "Submit" should start a download of all the receipts submitted between those dates combined into PDF form

#### Pending Advisor List
![image](https://user-images.githubusercontent.com/113213237/227038993-a7e3627e-0515-4ed7-9c53-177d9d1a0816.png)1. List should be all of the SABO #s of the requests with SABO #s assigned (ie. excluding reimbursement requests where the requester has not added a SABO #) and with status "Pending Advisor"
2. After "Sent To Advisor" is clicked, all listed reimbursement requests should have their status changed to "Approved" (chose "Approved" because this is the last step we can track ourselves and I didn't want to have something like "Pending SABO" be the final status)

#### Review SABO Request
![image](https://user-images.githubusercontent.com/113213237/227026827-bbff88db-c137-4ce6-aa8e-57b8b6b8d7b8.png)
1. The same as "View SABO Request" except it has "Approve" not grayed out
    - If there is an issue with a request, the finance team member should message the original submitter on Slack.
2. Clicking "Approve" should change this request's status to "Pending Advisor", then display, in plaintext, this information along with the corresponding SABO form field for the user to submit.
   - The following fields can be pulled from the Recipient's profile: First Name, Last Name, NUID, NEU Email, Phone #, Street Address, City, State, ZIP Code
   - The following fields on this page should be passed to the fields on the SABO form of similar/the same name: Date of Expense, Total Expenses
   - Expense Description on the SABO form should be the Purchased From field on FinishLine form with the total cost (eg. Bend & Snap Corp. [$1,000])
   - Business Purpose should be the list of WBS#s provided in the Products table (consider finding the project names corresponding to the WBS#s and listing that instead, capped at 140 characters).
   - SABO form Index field should be "800462"
   - Expense Type should translate to Account Code on the SABO form using the following mapping:
     - <img width="268" alt="image" src="https://user-images.githubusercontent.com/113213237/207199997-7980d7b4-def6-4279-bc5c-3e769232edd9.png">
   - SABO form fields regarding Student Group Treasurer should use Alex DeRing as the name and dering.a@northeastern.edu as the email
   - SABO form fields regarding Advisor/Supervisor should use Andrew Gouldstone as the name and a.gouldstone@northeastern.edu as the email
   - Any receipts uploaded to the Finishline form should be passed on to the Upload Receipts section on the SABO form
3. Once Puppeteer is added, this no longer has to show the plaintext version when "Approve" is clicked and should just fill out and submit this form on the SABO website automatically

#### Backend
 - [x] #1117 
 - [x] #1126 
 - [x] #1128 
 - [x] #1127 
 - [x] #1129 
 - [x] #1130 
 - [x] #1131 
 - [x] #1132 
 - [x] #1133  
 - [x] #1135 
 - [x] #1137 
 - [x] #1138 
 - [x] #1139 
 - [x] #1142 
 - [x] #1143 
 - [x] #1144 
 - [x] #1145 
 - [x] #1179
 - [ ] #1177 
 - [x] #1150 

#### Frontend
  - [x] #1213 
  - [x] #1214 
  - [x] #1215 
  - [x] #1216 
  - [x] #1217 
  - [x] #1218 
  - [x] #1219 
  - [x] #1220 
  - [x] #1221 
  - [x] #1222 
  - [x] #1260
  - [x] #1261
  - [x] #1262

**Comment by mccauleyma** [comment]
Purchased from should probably also be a searchable/autocompleting list of vendors. 90% of our purchases are from a small group of frequent vendors

**Comment by mccauleyma** [comment]
Regarding "new SABO form" are we automating the filling of the form or is this to be filled out after filling the SABO form? If we are _not_ automating I assume this is filled out after and we would require the generated SABO form to be entered into this system. We would then also want to change the "expense type" to match the numerical codes, instead of names potentially, or show both, since the number is what you have to enter into the SABO form.

**Comment by Peyton-McKee** [comment]
Dates stored in finishline do not have to be exactly when it happened, but can instead be the date that someone in NER confirmed that the event happened. This is James’ concept of the lifecycle of SABO tracked expenses.
- date purchased
- date submitted (finishline)
- date finance approved
- date submitted (SABO)
- date advisor approved
- date items delivered
- date reimbursed

**Comment by tom-weatherbee** [comment]
what did you want to change, idk if i'm understanding

but here's how i'd initially intended to track those dates

* date purchased -- Tracked under "date of expense"
* date submitted (finishline) -- Timestamped as soon as finishline request is submitted
* date finance approved -- Timestamped as soon as finance approves on finishline
* date submitted (SABO) -- Ideally as part of the finance team block finance will start submitting sabos as soon as they approve, as per Alex, so should be the same as date finance approved
* date advisor approved -- We have no way of knowing this, just confirmed with Alex
* date items delivered -- Tracked using "mark delivered"
* date reimbursed -- We have no way of knowing this, as per Matt et. al at last large discussion

**Comment by mccauleyma** [comment]
No we can figure out the date of reimbursement, it's just that we can't do it on our own. We need to request the records from SABO

**Comment by RChandler234** [comment]
MVP has been done for a fat minute, we've moved all improvement to this feature to #1274
