### ISSUE TITLE
Research - Code Documentation Tools

### ISSUE THREAD

**Issue by jamescd18** [Northeastern-Electric-Racing/FinishLine#5]
With the increasing complexity of the application and its code base, it's more important than ever to keep the code documentation up to date and readable. When doing this for a recent issue, I stumbled across [this article](https://react-styleguidist.js.org/docs/documenting/) about documentation for React components. That lead me to wonder what sort of tools might be out there to help us build user friendly documentation from code files and JSDoc. I know [Storybook](https://storybook.js.org) is a great thing that contrasts [Angular Playground](https://angularplayground.it), so those are good things to peek at.

--

- [ ] Read the styleguidist article on documenting React components
- [ ] Research common practices for documentation of React components
- [ ] Read about Storybook
- [ ] Read about Angular Playground (just for awareness)
- [ ] Research more about Storybook
- [ ] Summarize your findings and offer a suggestion

**Comment by anthonybernardi** [comment]
this ticket is too vague and also not really needed -- if anything we hsould just add jsdoc everywhere and maybe some github docs
