### ISSUE TITLE
General - Clean Up Test Warnings

### ISSUE THREAD

**Issue by acd124** [Northeastern-Electric-Racing/FinishLine#50]
### Description

Though all tests written and merged into main must pass before merging, many tests still emit warnings, resulting in a very messy output from the tests. This is not ideal, as some warnings might be warning us about real issues, and we don't read them because there are too many to sift through. We also do not want to simply suppress the warnings without addressing the issue, as that might cause issues later when writing tests if the issue is actually a problem.

### Background

This issue mostly involves working with our testing library Jest, but may involve more intimate work with React as many of the warnings are about how best to use react features. Warnings may cover things like using `act` for performing actions in tests, using the `key` prop properly, using the right props for Form elements, and an error being intentionally thrown but still emitted as a warning.

**Comment by jonathan-chen10** [comment]
Leaving this as a reminder: Anthony suggests mocking hocks using `mock-hooks.ts`, see f365acce5047aae72bfe40a7fca78c43e03d03b5
