### ISSUE TITLE
General - Gantt Chart Controls

### ISSUE THREAD

**Issue by jamescd18** [Northeastern-Electric-Racing/FinishLine#530]
## Overview

Visualizing all projects in FinishLine on a Gantt chart quickly becomes unwieldy as there are over 70 different projects with timelines spanning over 90 weeks. Let’s add controls to the overall Gantt chat page to make this more manageable.

## Stakeholders

Product Stakeholder: @jamescd18 
Software Stakeholder: @RChandler234 
Reference Users: Casey Sauer

## User Story

As a user, I want to view an overview Gantt chart of just the most relevant projects. Relevance may include focusing on a particular car, a particular team, projects of a specific status, or any number of combinations of those attributes and more.

## Acceptance Criteria

Add a filters panel page block to the top of the Gantt page for all the following filters to live.
- Filters should live update the Gantt chart displayed. When I select a new option, the Gantt charts automatically update without any additional user actions.
- Changes to filter state must be reflected in the URL to allow users to share filtered page states.

Specific Filters
- Car: Provide a checkbox for each car to allow selection of one or multiple cars. Default is all cars selected.
- Status: Provide a dropdown with options for every project status, plus an initial “All Statuses” option. Default is “ACTIVE”.
- Team: Provide a dropdown with options for every team, plus an initial “All Teams” option. Default is “All Teams”.

Timeline Filters
- Start Date: Provide a date picker for narrowing the timeline viewport to begin at the specified date. Default is blank to display the earliest date of all timeline data.
- End Date: Provide a date picker for narrowing the timeline viewport to end at the specified date. Default is blank to display the latest date of all timeline data.

Expand / Collapse
- Justify these buttons on the right side of screen within the page block.
- Provide an “Expand” button that will cause all projects in the Gantt chart to be expanded to display their work package timeline data. Use the "UnfoldMore" icon as a start icon to the "text" (aka default) style button.
- Provide a “Collapse” button that will cause all projects in the Gantt chart to be collapses to display only the project’s overall timeline data. Use the "UnfoldLess" icon as a start icon to the "text" (aka default) style button.

## Mocks
![FinishLine-Gantt-Controls-1](https://user-images.githubusercontent.com/51571627/211223808-0a09f193-a2a6-4bf7-85c6-1b66a9f9ac5c.jpeg)

**Comment by RChandler234** [comment]
Would a project lead/ project manager filter be useful, so someone could look at the gantt chart for all the projects that they're lead/manager on. We could have a default option that's "All Projects" or "No Specified Lead" or smthn.

**Comment by RChandler234** [comment]
Also on a UI note, I think having all the filters in a flat line like this looks a bit weird. At minimum I think we should group the checkboxes on the left, and the buttons on the right differently from the rest of the selects, so it's clear visually that the checkboxes are both under the car filter, and that the buttons are also closely associated with each other.

**Comment by jamescd18** [comment]
> Would a project lead/ project manager filter be useful, so someone could look at the gantt chart for all the projects that they're lead/manager on. We could have a default option that's "All Projects" or "No Specified Lead" or smthn.

Theoretically yes, but because for the following reasons, I thought it would be better to just skip it. Engineering leads are not really supposed to be leading multiple projects at a time and realistically only lead max 2 projects at once. Additionally, overall Gantt is intended for viewing timelines across multiple projects and typically a wholistic view for folks that manage a team and not just an individual project. For info about a specific project, it's easier to just view the project's gantt.

> Also on a UI note, I think having all the filters in a flat line like this looks a bit weird. At minimum I think we should group the checkboxes on the left, and the buttons on the right differently from the rest of the selects, so it's clear visually that the checkboxes are both under the car filter, and that the buttons are also closely associated with each other.

I'm not entirely sure what you mean here, potentially partly because I haven't played around with the gantt branch. If you're just suggesting we left-justify the filters and right-justify the expand/collapse buttons, then yeah absolutely I'm down for that (and updated the ACs). We can also use icons with the expand/collapse. With the mocks there just wasn't the room lol. Mocks are definitely not to-scale.

I went with a horizontal filters panel because I wanted to maximize horizontal screen real estate for users viewing the gantt and I wanted to give it a try. Having a filter panel on the lefthand side like we previously had for projects and change requests meant that if the filter didn't fill the whole page vertically, there was wasted space that could have made the content wider and more viewable (in this case more horizontal screen real estate means more time visible).

**Comment by anthonybernardi** [comment]
agree that filters definitely needs to be above the gantt chart. also agree with the idea of having the checkboxes be aligned in a vertical column instead of horizontal and same with with the expand/collapse buttons together.

**Comment by Ari-S-123** [comment]
https://github.com/Northeastern-Electric-Racing/FinishLine/pull/620
