### ISSUE TITLE
[Tech Debt] - Change MUI Labels to Form Labels

### ISSUE THREAD

**Issue by RChandler234** [Northeastern-Electric-Racing/FinishLine#532]
### Description

Currently in a couple places, we use typographies to label input boxes rather than formal labels and form controls like we should. We wanna use form labels because they look better and are easier to change how we want. We want to update all the spots listed to use FormControls and Form Labels (see the CreateProjectFormView).

Project Edit - Project edit uses this built in label prop mui has, but I don't like it, it's prone to weird bugs and isn't worth the trouble imo, so we're switching to a formcontrol with form label on all the inputs in this file. If you have more questions about that, just slack me in a channel - Reid
Work Package Edit - same as Project Edit

### Acceptance Criteria

All the listed forms use the form label instead of typographies. 

### Proposed Solution

See CreateProjectFormView for examples of how to do this.

**Comment by tharitRT** [comment]
I don't see any `FormControls` or `FormLabel` in `CreateProjectFormView.tsx`. When you said "We want to update all the spots listed to use FormControls and Form Labels". Did you mean this [FormLabel](https://mui.com/material-ui/api/form-label/)?

**Comment by RChandler234** [comment]
It's in a PR rn, I didn't expect this ticket to be picked up so quickly tbh. What's your @ in slack, that's usually where we put questions like this?
