### ISSUE TITLE
CR Creation - sort the wbs dropdown

### ISSUE THREAD

**Issue by anthonybernardi** [Northeastern-Electric-Racing/FinishLine#536]
### Description

on the cr creation page, the things in the wbs dropdown are unsorted (see on prod or make a bunch of projects and work packages)

### Acceptance Criteria

make the options list be sorted by wbs num

note: make sure things like `1.1.10` comes after `1.1.9` even though if you just sort alphabetically 1.1.9 comes first

### Proposed Solution

use the `sort` function with a custom predicate to sort the options

i think the tables do this? not sure

**Comment by superhvarn** [comment]
Already done

**Comment by superhvarn** [comment]
nvm I just finished it
