### ISSUE TITLE
Frontend - Dependencies display need a space

### ISSUE THREAD

**Issue by anthonybernardi** [Northeastern-Electric-Racing/FinishLine#543]
### Observed Behavior

dependenceis are displayed like on the work package summary card `Dependencies:1.1.0, 1.1.1`

### Expected Behavior

they should be displayed like `Dependencies: 1.1.0, 1.1.1` (note the space)

### Steps to Reproduce

1. go to a project page
2. scroll down to work packages
3. expand one that has dependencies
4. see that there is no space

### Screenshots (as needed)

![Screenshot 2023-01-16 at 11 12 32 PM](https://user-images.githubusercontent.com/63663597/212808479-5b83ef8b-c025-4921-b368-b40ab09d61b8.png)

**Comment by Ray-kong** [comment]
<img width="1306" alt="스크린샷 2023-01-19 오후 7 53 44" src="https://user-images.githubusercontent.com/58490052/213594866-8797b119-94b4-4bc7-8bd5-00abc3730973.png">

I was not able to reproduce it
