### ISSUE TITLE
Create WP Form Deliverables Typo

### ISSUE THREAD

**Issue by anthonybernardi** [Northeastern-Electric-Racing/FinishLine#544]
### Observed Behavior

the create work package form says `Deliverabless`

### Expected Behavior

it should say `Deliverables`

### Steps to Reproduce

1. go to the change requests page
2. go to a change request that has already been approved
3. click actions in the top right then "create new work package"
4. see that the "Deliverables" is spelled wrong

### Screenshots (as needed)

![image](https://user-images.githubusercontent.com/63663597/212808710-c0acc169-444e-4b9f-a702-6fc67c05913f.png)

**Comment by winniechuma** [comment]
Done! This was fixed; Deliverables was spelled correctly

![Image](https://user-images.githubusercontent.com/113949809/217068155-a23be1c2-726c-4b1a-96ac-00666077d2da.jpeg)



![Image](https://user-images.githubusercontent.com/113949809/217068203-5c6a535f-7285-4c71-a7bf-1f86cfb9c7cb.jpeg)
