### ISSUE TITLE
[Frontend] - New Change Request Button Color

### ISSUE THREAD

**Issue by Ari-S-123** [Northeastern-Electric-Racing/FinishLine#549]
### Browser(s)

Chrome, Other (specify below)

### Platform(s)

Desktop

### Version(s)

production (main)

### Observed Behavior

The color of this button when the cursor is not hovering over it is `#ff0000`, which doesn't match the header.

### Expected Behavior

The color of this button when the cursor is not hovering over it should be `#ef4345`: **NER RED**. If the cursor is hovering over it, only then should it become `#ff0000`.

### Steps to Reproduce

1. Go to https://finishlinebyner.com/change-requests 
2. Observe the color of the button, right-click it and click 'inspect' and note the hex value of `background-color`. It doesn't match the header.

### Screenshots (as needed)

![image](https://user-images.githubusercontent.com/80832201/213276579-7d957d55-b63e-4709-9d06-a3b6fb807dfc.png)

**Comment by anthonybernardi** [comment]
also im pretty sure it's just bright red when you're a guest because it's disabled so that should be fixed too
