### ISSUE TITLE
General - Research structure for front end organization and make write-up of front-end practices

### ISSUE THREAD

**Issue by jpwaves** [Northeastern-Electric-Racing/FinishLine#55]
### Spike Type

Technical

### Goal

Improve the organization of front-end components and overall project structure for things related to front-end, and create a wiki or docs page listing out what practices and style we want to use for all our front-end files.

### Reason for Spike

To standardize our practices so it's easier for new devs to onboard and all our code follows best practices (to some extent)

### Additional notes

may need to look into how we want to also test front-end components too and make a doc on that

**Comment by anthonybernardi** [comment]
we implemented most of this yahoo
