### ISSUE TITLE
Projects - Fix work package edit form progress to allow setting progress to 0%

### ISSUE THREAD

**Issue by jinhyunh** [Northeastern-Electric-Racing/FinishLine#56]
## Description
Add option in work package edit form to have 0% progress. 

## Background
In the dashboard currently, there are only 4 options for the progress:
- [ ] 25%
- [ ] 50%
- [ ] 75%
- [ ] 100%

There should be an option to set a work package progress to 0% but as shown in the screenshots, there are none.

## Proposed Solution
Add an option for 0% progress in the work package edit form

## Screenshots
This screenshot was taken in the work package edit form for Projects >> Impact Attenuator >> Bodywork Concept of Design
![image](https://user-images.githubusercontent.com/69995430/163887304-2a962c07-5b2f-4411-a73e-29403e183b7e.png)

**Comment by anthonybernardi** [comment]
this is not true anymore
