### ISSUE TITLE
General - Standardize Work Package and Project Edit Endpoints

### ISSUE THREAD

**Issue by RChandler234** [Northeastern-Electric-Racing/FinishLine#57]
### Description

The work package and project edit endpoints use a slightly different way of taking in the input and therefore the exact same helpers aren't used.

### Background

You will need to know how both endpoints work from frontend to backend

### Proposed Solution
1. figure out how the two endpoints expect input. main differences are the id values of new bullets -- wp expects -1 and project expects undefined -- and project lead/manager are different too I think?
2. standardize the endpoints to treat the inputs the same way
3. standardize the utils functions that they use. now we should only need one set of them instead of two
4. change how the frontend calls these endpoints to make sure it still works
5. test it manually a lot to make sure nothing is broken

**Comment by anthonybernardi** [comment]
we are gonna go about this differently in the future by splitting up these endpoints so this is unecessary work
