### ISSUE TITLE
Projects - Critical Path Gantt Chart Investigation

### ISSUE THREAD

**Issue by leoRysing** [Northeastern-Electric-Racing/FinishLine#59]
## Spike Type

Functional

## Goal

The goal is to investigate and implement in Critical Path into the Gantt Chart for an individual project.

## Reason for Spike

Critical Path is incredibly helpful for visualizations of dependencies within a project. It [Critical Path] highlights which work packages are driving the overall timeline. These work packages are more critical to ensure do not get delayed significantly, so it is useful to highlight these work packages.

**Comment by anthonybernardi** [comment]
redundant now with new gantt stuff
