### ISSUE TITLE
Projects - Allow Users to see Engineers that are working on Project And Work Package

### ISSUE THREAD

**Issue by jinhyunh** [Northeastern-Electric-Racing/FinishLine#61]
### User Stories

epic

### Background

Currently, the only engineers visible in a project and a work package are the project leads and project managers. This needs to be expanded so that all engineers working on a given project and/or work package are shown.

### Tickets

 - [ ] Northeastern-Electric-Racing/FinishLine#60
 - [ ] #

**Comment by anthonybernardi** [comment]
unfinished ticket and epic
