### ISSUE TITLE
[DevOps] - Look into using an actual bundler

### ISSUE THREAD

**Issue by RChandler234** [Northeastern-Electric-Racing/FinishLine#619]
### Goal

Get rid of Create React App to hopefully make the app run faster/ give us more control and customization over our app.

### Reason for Spike

We used Create React App to get started because it was easy and got rid of a lot of the annoying Dev-Ops parts of starting a website, but now that we're a larger application I would argue that it's probably time to move away from it to give us more control over our App. Additionally, this might allow us to upgrade to Node 18 (neat!)

### Additional notes

Current options are using webpack (which Create React App already is under the hood), or Vite which is newer/ a little faster/niftier.

**Comment by acd124** [comment]
https://dev.to/nikhilkumaran/don-t-use-create-react-app-how-you-can-set-up-your-own-reactjs-boilerplate-43l0

**Comment by ninest** [comment]
```ts
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [react()],
  build: {
    sourcemap: true
  },
  resolve: {
    preserveSymlinks: true
  }
});
```

`preserveSymlinks` is required for yarn workspaces to work.

I also had to add this middleware in `backend/index.ts`:

```ts
app.use(function (req, res, next) {
  res.header('Access-Control-Allow-Methods', 'GET,HEAD,OPTIONS,POST,PUT');
  res.header('Access-Control-Allow-Headers', 'Origin, X-Requested-With, Content-Type, Accept, Authorization');
  next();
});
```

But it seems like cookies aren't being saved:

```
{"stack":"Error: Authentication Failed: Not logged in (dev)!\n at http://localhost:3000/src/utils/axios.ts:12:13\n at async Object.queryFn (http://localhost:3000/src/hooks/users.hooks.ts:47:22)","message":"Authentication Failed: Not logged in (dev)!"}
```

**Comment by ninest** [comment]
Change `process.env.NODE_ENV` to `import.meta.env.MODE`
