### ISSUE TITLE
[Frontend] - Add unit of time to proposed solution form

### ISSUE THREAD

**Issue by RChandler234** [Northeastern-Electric-Racing/FinishLine#623]
### Description

Right now the proposed solution form does not specify a unit for Timeline Impact when you're entering it. When you submit the form correctly you'll see that the unit of time is weeks. While this is a small detail/ most people who are filling this out will know it's weeks, it shouldn't be a hard change, so I see no reason not to update it.

IMPORTANT NOTE: Don't take this ticket unless you're a new dev. I will just close your PR and get annoyed at you. Please and Thank You.

### Acceptance Criteria

Update this form to say "# of weeks needed" rather than just "# needed" before you type any value in. 
![image](https://user-images.githubusercontent.com/29521172/213883059-5a3c47b6-4adf-4015-b031-8a8af249ba2d.png)

### Proposed Solution

You're probably gonna need to change a prop on a React component in whatever file this form is in. If you don't know what any of those words mean, I'd do some research first and then ask a question in slack/ in a meeting if you can't figure it out.

**Comment by aar-ish** [comment]
Hey, I would like to contribute to this!

**Comment by strawHat121** [comment]
Can I take this ?
