### ISSUE TITLE
[DevOps] - Migrate to Node 18

### ISSUE THREAD

**Issue by Ari-S-123** [Northeastern-Electric-Racing/FinishLine#625]
### Description

Migrate from Node 16 to Node 18. Node 16 will be at its End-of-Life on September 11, 2023, so this ticket should be completed by then.

### Acceptance Criteria

There should not be any regressions from the migration, all features should work the same as before.

### Proposed Solution

Run the app with node 18 and fix any issues that arise.

**Comment by acd124** [comment]
Problem: error:0308010C:digital envelope routines::unsupported
Solution: Upgrade react-scripts to version ^5.0.1
https://www.freecodecamp.org/news/error-error-0308010c-digital-envelope-routines-unsupported-node-error-solved/

**Comment by acd124** [comment]
Problem 2: ERROR in src/tests/pages/ChangeRequestDetailPage/ReviewChangeRequest.test.tsx:16:9
Something about missing wbsName in a type. This is a skipped test, so commenting it out works, should get a fix for this somewhere else first.

**Comment by acd124** [comment]
It might work after that, there was something related to this https://stackoverflow.com/questions/63912721/failed-to-load-config-react-to-extend-from but clicking x on the error let me just do stuff. This needs far more thorough testing, but I'd say the spike aspect is mostly done. There are still a lot of dependencies that are very outdated, but the app functions as is on node 18.

**Comment by acd124** [comment]
Problem 3: [eslint] Failed to load config "react-app" to extend from.
Solution should involve adding the react app eslint config as a dev dependency, might have to resolve version conflicts with react scripts

**Comment by acd124** [comment]
Problem 4: Backend giving 500 errors with Error Unknown

**Comment by acd124** [comment]
Regarding Problem 3: eslint for react
The root of the issue appears to be somewhere in react-scripts which may have a solution related to #619. This error does not affect normal app usage but may be a consistent annoyance in development.

**Comment by ninest** [comment]
@acd124 Does vite (#619) fix this 👀

**Comment by acd124** [comment]
> @acd124 Does vite (#619) fix this 👀

Everything looks like it does, yes. I've run the app several times on node18 no issues from a blank slate develop branch. The other minor issues I documented here are likely not impacting regular development when using vite.
