### ISSUE TITLE
[Frontend] - Change UserSettingsEdit to use NER Buttons

### ISSUE THREAD

**Issue by RChandler234** [Northeastern-Electric-Racing/FinishLine#685]
### Description

In the pursuit of making the looking and feel of our app consistent, we wanna use new components that have been made (NERSuccessButton/NERFailButton) in every place where we currently have a cancel/save button combo. By doing this, we not only make all these save/cancel buttons adhere to the new look, but we also allow ourselves to change how all these save buttons look in the future by changing only one file!

For this ticket, change the save/cancel buttons in the UserSettingsEdit component to use the NERSuccessButton/NERFailButton component rather than just the plain MUI button. 

Put the cancel on the left, and the submit on the right

### Acceptance Criteria

The save/cancel buttons on UserSettingsEdit use NERSuccessButton/NERFailButton and not Button
The save/cancel buttons on that page looks like the new success/cancel buttons (green and red contained, see the edit members section on a teams specific page to see a good example of how it looks).
Verify nothing looks weird/ everything works as it did before.

### Proposed Solution

All the props should be the same, all you need to do is swap out the old <Button> for the new <NERSuccessButton>/<NERFailButton> for the Save/Cancel buttons respectively.

**Comment by Mayuresh0072** [comment]
@RChandler234 @hams7504 Hello, I want to work on this issue and contribute.. Please assign me this issue. Thanks
