### ISSUE TITLE
CI/CD - Plan potential new GitHub workflows

### ISSUE THREAD

**Issue by jamescd18** [Northeastern-Electric-Racing/FinishLine#7]
Creating an issue to help keep some notes and planning around potentially creating new GitHub workflows for various different functionality related to CI/CD DevOps items.

Potential use cases:
- Production database adjustments
- Manually triggering jobs
- code security checks

Resources:
- [GitHub Docs - Events that trigger workflows](https://docs.github.com/en/actions/reference/events-that-trigger-workflows)
- [GitHub Docs - Workflow syntax for GitHub Actions](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idif)
- [GitHub Docs - Context and expression syntax for GitHub Actions](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#about-contexts-and-expressions)
- [Fireship Tutorial](https://www.youtube.com/watch?v=eB0nUzAI7M8)
- [GitHub Security CI/CD Video](https://www.youtube.com/watch?v=O7BcaCBka54)

**Comment by anthonybernardi** [comment]
too vague, tickets need to be actionable
