### ISSUE TITLE
Projects - Fix Out of Bounds Names in Gantt Chart

### ISSUE THREAD

**Issue by leoRysing** [Northeastern-Electric-Racing/FinishLine#71]
### Browser(s)

Chrome

### Platform(s)

Desktop

### Version(s)

main

### Observed Behavior

If a work package name is too long, its name goes out of bounds of the gantt chart; the leftmost characters get lost.

### Expected Behavior

We want either to fix the spacing, or to truncate the rightmost characters to be able to fit the whole name.

### Steps to Reproduce

Reproduce this bug mainly by opening a project that has a work package with a long enough name.

**Comment by anthonybernardi** [comment]
we're changing gantt package
