### ISSUE TITLE
General - Replace Backend Error Handling with `http-errors`

### ISSUE THREAD

**Issue by jamescd18** [Northeastern-Electric-Racing/FinishLine#75]
### Description

Replace our current `buildErrorResponse` functions with usage of throwing errors using this package [`http-errors`](https://www.npmjs.com/package/http-errors)

### Background

We first built the back-end without much knowledge of how to build serverless backends. We built out the backend to first do returns of good data, but then we started needing error handling. I wanted to ensure we could have error messages, and do it in a flexible way with abstraction and reducing hard-coded copy-pasted stuff, so we built out the `buildResponse` functions for error handling.

### Proposed Solution

 this package [`http-errors`](https://www.npmjs.com/package/http-errors) is compatible with middyjs error handling as seen here: https://middy.js.org/docs/middlewares/http-error-handler

**Comment by anthonybernardi** [comment]
express
