### ISSUE TITLE
General - Replace Mock Component with Builder Function

### ISSUE THREAD

**Issue by jamescd18** [Northeastern-Electric-Racing/FinishLine#76]
### Description

Replace the repeated basic component mocking boilerplate with a builder function to avoid code duplication and shorten test files.

### Background

In order to mock out a react component, we use this boilerplate code, replacing just the import statement and the text inside the div

<img width="460" alt="Screen Shot 2022-06-30 at 11 45 11 PM" src="https://user-images.githubusercontent.com/51571627/176839354-34bed655-cd05-4745-a7b2-a56b310857d0.png">

this helps us avoid loading it tons of heavy components when we're not trying to test that component's behavior.

### Proposed Solution

Create a function in the test support utils that generates the function right after the file import string in the screenshotted example above, taking in just a string as the input, that is used for the string inside the div. Then implement this function throughout the application.

**Comment by anthonybernardi** [comment]
i found a different approach that we can use instead
