### ISSUE TITLE
[Frontend] - Gantt Projects & Work Packages Sort Order

### ISSUE THREAD

**Issue by Ari-S-123** [Northeastern-Electric-Racing/FinishLine#777]
### Browser(s)

Chrome

### Platform(s)

Desktop

### Version(s)

production (main)

### Observed Behavior

The projects and work packages in the Gantt Chart on the Gantt Page appear by their order in the database.

### Expected Behavior

They should be sorted by their WBSNum.

### Steps to Reproduce

1. Go to the Gantt Page
2. Observe the order of the projects
3. Expand and observe the order of work packages

### Screenshots (as needed)

![image](https://user-images.githubusercontent.com/80832201/215865800-fa0c66eb-944d-4f1a-ad31-95ab0ab21295.png)

**Comment by ahnfikd7** [comment]
What is a WBSNum?

**Comment by anthonybernardi** [comment]
unassigning ahnaf since he is still working on this one https://github.com/Northeastern-Electric-Racing/FinishLine/issues/846
