### ISSUE TITLE
[Spike] - Slack Notifications1

### ISSUE THREAD

**Issue by RChandler234** [Northeastern-Electric-Racing/FinishLine#795]
Look into slack notifications that ping people on slack one day before a task they are assigned to is due. This spike would involve setting up an MVP of whatever method you think is viable. The one idea we have right now, is a github action that runs once a day to hit an endpoint in the backend that would check for all relevant pings. Another way would be to look into setting up cron jobs with something like this: https://www.npmjs.com/package/cron

**Comment by jonathan-chen10** [comment]
Idea: try https://api.slack.com/messaging/scheduling

test if user has slack id, if no ID then do nothing
on task creation: schedule a DM
on task assignee/deadline update or moved back from done: delete and re-schedule DM
on task marked as done: delete DM

**Comment by RChandler234** [comment]
I think you can have github actions run at a specific time, so if nothing else, we could set one up to run once a day to hit an endpoint that checks if any deadlines are upcoming, and sends out slack notifs if they are
