### ISSUE TITLE
[Frontend] - Add 0 to Car Number Filter on Gantt Page

### ISSUE THREAD

**Issue by Ari-S-123** [Northeastern-Electric-Racing/FinishLine#838]
### Description

Currently, the Car Number filters on the Gantt Page only include 1 and 2 as options. 0 needs to be added as an option to account for projects with Car Number 0.

### Acceptance Criteria

The Car Number filters should include 0, 1, and 2.

### Proposed Solution

Follow the pattern used for Car Numbers 1 and 2 and add a button and the relevant code additions for Car Number 0 in `GanttPageWrapper.tsx` and `GanttPageFilter.tsx`.

### Mocks

![Screenshot 2023-02-07 122612](https://user-images.githubusercontent.com/80832201/217319131-4b7ca954-c3c2-4aac-b711-4941d57c464d.png)

**Comment by haoming5674** [comment]
I believe 0 isn't an option available in the @mui/icons-material package. https://mui.com/material-ui/material-icons/?query=Looks shows 1 as the lowest possible icon, so how can I get it to show 0?
