### ISSUE TITLE
Projects - Improve Project Links

### ISSUE THREAD

**Issue by jamescd18** [Northeastern-Electric-Racing/FinishLine#857]
## Overview

On projects, in their section with links, replace the Slide Deck link with a link to a Confluence page.

### Stakeholders

Product Stakeholder: James Chang-Davidson
Software Stakeholder: TBD
Reference Users: Matthew McCauley

### User Story

As a user, I want to see links to confluence instead of slide decks, so that I can access the appropriate resources for my projects.

### Success Metrics

N/A

### Rollout Plan

Rollout may require dealing with the confluence links that users have put into the slide deck field as a temporary workaround.

### Out of Scope

TBD

### Background / Context

Projects were originally built with a fixed 4 fields because those were the linked external resources not being implemented into FinishLine when we first built it. This was also a limitation of our knowledge at the time.

### Roughly Speaking
- Future additions and removals of links on a project or in FinishLine are more flexibly implemented
- Slide deck links are removed
- Confluence links are added
- Google drive links store just the folder ID, enabling usage in Google Drive API calls
- BOM links store just the spreadsheet ID, enabling usage in Google Sheets API calls
- Task list links are removed once Task Lists are deployed to production

### UX for adding links

Links should no longer be a single static field to paste a link in.
- When in edit mode on a project, an “add link” set of entry fields is available below all existing links
  - There should be a dropdown for selecting the type of link to add: Google Drive, Google Sheet, Confluence
  - The add link button should be an icon button using the AddLinkIcon
- When clicked, a new row of fields is presented to the user above the “add link” button
  - 

## Tickets

 - [ ] #
 - [ ] #

**Comment by RChandler234** [comment]
Made into Product Inquiry
