### ISSUE TITLE
Projects - Improve Layout of Form Fields

### ISSUE THREAD

**Issue by jamescd18** [Northeastern-Electric-Racing/FinishLine#899]
## Description

Improve the layout of input fields in all forms to make the most of the screen real estate.

## Acceptance Criteria & Mocks

Ensure everything still works responsively with proper dynamic resizing of the screen. There's a "fullWidth" boolean property that can be used.

**Project Page Edit Mode**
<img width="1619" alt="image" src="https://user-images.githubusercontent.com/51571627/219938137-05828fd8-8aa3-4b74-8df9-e26034e0319a.png">

- project manager and project lead can probably fit to the right of budget
- all four links should be full width
- budget can probably be a little bit smaller if it's easy

**Project Page Edit Mode (con't.)**
<img width="1619" alt="image" src="https://user-images.githubusercontent.com/51571627/219938310-6b5d91de-eeba-4be2-84f6-16cad278bd5a.png">

- summary box should definitely be full width
- bullet fields look like they could be more full width since the trash icon isn't actually all the way on the furthest right it could be
- bullet fields should be dynamically multi-line if the content is longer than one line

**Work Package Page Edit Mode**
<img width="1614" alt="Screenshot 2023-02-19 at 3 57 27 AM" src="https://user-images.githubusercontent.com/51571627/219938590-4b895df2-53f8-402d-b2b4-53a75419b7ce.png">

- duration can be smaller if it's easy
- duration can go to the right of start date
- project lead and project manager should moreso match how the project edit mode ones look
- dependencies can be added and aligned horizontally instead of vertically
- dependencies should also probably have an error message when they aren't WBS numbers
- same note about bullets being full width
- breadcrumb project name

**New Project Form**
<img width="1637" alt="Screenshot 2023-02-19 at 4 01 10 AM" src="https://user-images.githubusercontent.com/51571627/219938772-c4504321-1d62-43a5-84ee-be9ede05c695.png">

- project name needs to be wider
- project name, car number, team, and CR ID can all go in one line in that order
- project summary should be full width
- add fields for links, goals, features, other constraints, and rules
- create cancel buttons should be right aligned and swap places

**New Work Package Form**
<img width="1615" alt="Screenshot 2023-02-19 at 4 07 55 AM" src="https://user-images.githubusercontent.com/51571627/219939071-8d34f130-d247-4a7f-a2a6-d498f8ef2989.png">

- I think we can fit name, start date, duration, project WBS, and CR ID all on one line, no?
- dependencies horizontal instead of vertical
- same idea of bullet fields being more full width
- same idea of create cancel buttons should be right aligned and swap places

**Activate WP Form**
<img width="403" alt="Screenshot 2023-02-19 at 1 31 11 PM" src="https://user-images.githubusercontent.com/51571627/219967851-d8231255-c878-49bb-90ca-5b7b34886ff3.png">

- this modal looks weird when it's so skinny
- order things as project lead and project manager on one line
- then order things as start date and confirmation on another line
- ensure things are still responsive and dynamically resize with available screen real estate

Tickets:

- [x] #923 
- [x] #924 
- [x] #925 
- [x] #926 
- [x] #927

**Comment by RChandler234** [comment]
this been done
