### ISSUE TITLE
Change Requests - Move Status Logic to Back-End

### ISSUE THREAD

**Issue by jamescd18** [Northeastern-Electric-Racing/FinishLine#93]
## Description

Move the business logic of change request status to the back-end. The business logic of change request status should only be in the back-end and the front-end should read from the back-end.

## Background

All change requests have a status. This logic relating to determining the status of a change request currently overlaps with the front-end. As of now, we wrote the logic of change request status in the front-end (mainly cause of laziness), but we should move it to the back-end.

## Business Logic
The status of a change request depends on fields within the change request. The change request will be referred to as `cr`.
- If the cr’s `changes` array is not empty, then the status should always be `IMPLEMENTED`
- If the cr’s `changes` array is empty, the cr’s `accepted` field is true, and the cr’s `dateReviewed` field is not empty, then the status should be `ACCEPTED`
- If the cr’s `changes` array is empty, the cr’s `accepted` field is false, and the cr’s `dateReviewed` field is not empty, then the status should be `DENIED`
- If it doesn't fit any of the above criteria, then the status should be `OPEN`

## Proposed Solution

Move business logic of change request status to the back-end. In other words, the back-end would be responsible for determining the status of a change request. The front-end should read this status from the back-end, and then display it.

- [x] Create the `changeRequestStatus` enum in the `shared` package
  - The enum should have 4 values: `IMPLEMENTED`, `ACCEPTED`, `DENIED`, and `OPEN`
- [x] Add the field to the `ChangeRequest` interface and call it "status"
- [x] Update the `change-requests.stub.ts` test data
- [x] Update the change requests transformer to calculate the status of a cr
  - [x] Write a helper function to do the calculation in shared
  - [x] Utilize the helper function in the `changeRequestTransformer` function
- [x] Update the front-end to properly utilize the status field sent by the back-end
  - [x] Remove code from the front-end that computes which status to display (on table and on individual page)
  - [x] Have the front-end display the value provided by the back-end (on the table and an individual cr page)
  - [x] Update tests in the front-end to ensure they are still passing properly
- [x] manually ensure this new feature works properly and post a screenshot in your pr

**Comment by anthonybernardi** [comment]
note: this ticket is old af and i updated it but if it doesnt make sense or seems wrong please ask
