### ISSUE TITLE
Projects - Ensure Work Package Cannot Reference Self as Dependency in Create and Edit Forms

### ISSUE THREAD

**Issue by jamescd18** [Northeastern-Electric-Racing/FinishLine#94]
## Description

Make sure that the user can't add a work package's own WBS number as a dependency or the project that the work package is a part of as the work package's dependency. This functionality should be implemented in both the work package create form and work package edit form.

## Browser(s)

Chrome, Firefox, Safari

## Platform(s)

Desktop, iOS, Android

## Version(s)

main, production

## Observed Behavior

Currently, the application allows for a user to add a work package’s own WBS number to that work package’s list of dependencies. 

## Expected Behavior

- [ ] A user should not be able to set a work package to have itself as a dependency. 
- [ ] A user should not be able to set the project that a work package is within to be set as a dependency of the work package. 

Consider 1.1.1 which is a WP inside of 1.1.0. When adding dependencies to 1.1.1, don't allow the user to add 1.1.1 or 1.1.0 as dependencies.

## Proposed Solution

Look in the back-end where the work packages are created and edited, and ensure that WBS elements added to the dependencies list are not the same as the current work package or the project above. You should throw a 400 client error 
if an invalid dependency is attempted to be added. You will need to implement this functionality in 2 spots: 

- [ ] Work package create form
- [ ] Work package edit form

It is important to have this safeguard in all of these spots because users will have front-end form validation that errors early, before they click submit on the form. The back-end validation will also provide the stronger sense of security that the business logic will be correct. 

## Steps to Reproduce

Create a new work package with its anticipated WBS number in the list of dependencies. 

Edit a work package and add its WBSNumber to the list of dependencies. 

Create a new work package with the project WBSNumber also in the list of dependencies. 

Edit a work package and add the project it is in to the list of dependencies.

**Comment by anthonybernardi** [comment]
duplicate with #52
