### ISSUE TITLE
Tasks stuck on loading screen when project is not assigned to a team

### ISSUE THREAD

**Issue by Peyton-McKee** [Northeastern-Electric-Racing/FinishLine#956]
### Browser(s)

Chrome, Firefox, Safari

### Platform(s)

Desktop

### Version(s)

production (main), develop

### Observed Behavior

Tasks will have three loading indicators when the project is not on a team

### Expected Behavior

Tasks should just be empty if the project is not on a team

### Steps to Reproduce

1. go to genesis project
2. look at task list
3. or create a new project and dont assign a team

### Screenshots (as needed)

<img width="767" alt="Screen Shot 2023-03-02 at 12 16 27 PM" src="https://user-images.githubusercontent.com/113635669/222506149-7d579ad0-c014-44cb-b014-59ef7ca5b0cf.png">

**Comment by jonathan-chen10** [comment]
There are 3 loading indicators because the code to hide if the tab index is wrong only happens later on. Might be worth looking into a wrapper container for that. (mui's incubating TabPanel component should do that when it gets released)
