### ISSUE TITLE
General - Consider Adopting Ideas From Husker

### ISSUE THREAD

**Issue by jamescd18** [Northeastern-Electric-Racing/FinishLine#96]
## Spike Type

Technical

## Description

Look through the Husker project codebase to see what improvements can be made in our project.

## Goal

Various different improvements to the codebase, all inspired by reading through the codebase for the Husker project.

## Reason for Spike

It would improve the following:
- Improved formatting of className variables

Some helpful links for this are;
- [PDFEmbedProps interface](https://github.com/ninest/huskinfo/blob/301453c970b60376d513a739affcdd2687492bcc/components/PDFEmbed.tsx#L4)
- [className implementation in the Husker project](https://github.com/ninest/huskinfo/blob/301453c970b60376d513a739affcdd2687492bcc/components/PDFEmbed.tsx#L18
)

## Additional notes

[General Embedded PDF file](https://github.com/ninest/huskinfo/blob/main/components/PDFEmbed.tsx)

**Comment by anthonybernardi** [comment]
too vague, need actionable items/acceptance criteria
